import { type FactDocument, dump } from "@repo-facts/contract";
import { describe, expect, it } from "vitest";
import { parseYarnLock } from "../src/index.js";
import { type FileTree, profile } from "./support.js";

const json = (value: unknown) => `${JSON.stringify(value, null, 2)}\n`;

const facts = (document: FactDocument) => document.categories.resolved_dependencies!.facts;
const resolved = (document: FactDocument) => Object.fromEntries(facts(document).map((fact) => [fact.key, fact.state === "conflicting" ? fact.candidates!.map((candidate) => (candidate.value as { version: string }).version) : (fact.value as { version: string }).version]));
const locations = (document: FactDocument, key: string) =>
  facts(document).find((fact) => fact.key === key)!.evidence.map((id) => {
    const { path, location } = document.evidence[id]!;
    return `${path}${location.kind === "lines" ? `:${location.start}-${location.end}` : location.kind === "pointer" ? `#${location.pointer}` : ""}`;
  }).sort();

const YARN_LOCK = [
  "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
  "# yarn lockfile v1",
  "",
  "",
  '"@babel/code-frame@^7.0.0", "@babel/code-frame@^7.22.13":',
  '  version "7.24.7"',
  '  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.24.7.tgz#abc"',
  "  dependencies:",
  '    "@babel/highlight" "^7.24.7"',
  "",
  "lodash@^4.17.15, lodash@^4.17.21:",
  "  version 4.17.21",
  "",
  'react@^18.3.1:',
  '  version "18.3.1"',
  "",
].join("\n");

const WORKSPACE: FileTree = {
  "package.json": json({ name: "portal", private: true, workspaces: ["modules/*"], devDependencies: { "@babel/code-frame": "^7.22.13" } }),
  "modules/billing/package.json": json({ name: "billing", version: "1.2.0", dependencies: { lodash: "^4.17.21", react: "^18.3.1", ledger: "1.x" } }),
  "modules/ledger/package.json": json({ name: "ledger", version: "1.4.0" }),
  "yarn.lock": YARN_LOCK,
};

describe("Yarn classic lockfiles", () => {
  it("resolves quoted, unquoted, scoped, and multi-specifier headers through the declared specifier", async () => {
    const { document } = await profile(WORKSPACE);
    expect(resolved(document)).toEqual({
      "modules/billing/package.json#ledger": "1.4.0",
      "modules/billing/package.json#lodash": "4.17.21",
      "modules/billing/package.json#react": "18.3.1",
      "package.json#@babel/code-frame": "7.24.7",
    });
    // Evidence spans the entry header through its version line.
    expect(locations(document, "package.json#@babel/code-frame")).toEqual(["yarn.lock:5-6"]);
    expect(locations(document, "modules/billing/package.json#lodash")).toEqual(["yarn.lock:11-12"]);
    // Workspace packages are not locked by Yarn classic; they resolve to the member's declared version.
    expect(locations(document, "modules/billing/package.json#ledger")).toEqual(["modules/ledger/package.json#/version"]);
  });

  it("parses headers and ignores nested fields", () => {
    const parsed = parseYarnLock(YARN_LOCK);
    expect(parsed.ok && parsed.entries.map((entry) => [entry.specifiers, entry.version, entry.headerLine, entry.versionLine])).toEqual([
      [["@babel/code-frame@^7.0.0", "@babel/code-frame@^7.22.13"], "7.24.7", 5, 6],
      [["lodash@^4.17.15", "lodash@^4.17.21"], "4.17.21", 11, 12],
      [["react@^18.3.1"], "18.3.1", 14, 15],
    ]);
  });

  it("rejects lockfiles written by Yarn 2 and later", async () => {
    const { document } = await profile({ "package.json": json({ name: "app", dependencies: { react: "^18.3.1" } }), "yarn.lock": '__metadata:\n  version: 8\n\n"react@npm:^18.3.1":\n  version: 18.3.1\n' });
    expect(document.categories.resolved_dependencies).toMatchObject({ state: "unknown", search: { skipped: ["yarn.lock"] } });
    expect(document.diagnostics).toContainEqual(expect.objectContaining({ path: "yarn.lock", reason: "unsupported_version" }));
  });

  it.each([
    ["a header without a colon", "react@^18.3.1\n  version \"18.3.1\"\n", "Line 1: expected an entry header ending in a colon"],
    ["a field before any entry", '  version "18.3.1"\n', "Line 1: a field appears before any entry"],
    ["an unterminated quote", '"react@^18.3.1:\n  version "18.3.1"\n', "Line 1: the entry header is malformed"],
    ["a malformed version", 'react@^18.3.1:\n  version "18.3.1\n', "Line 2: the version is malformed"],
  ])("reports %s as a parse failure", async (_name, lockfile, detail) => {
    const { document } = await profile({ "package.json": json({ name: "app", dependencies: { react: "^18.3.1" } }), "yarn.lock": lockfile });
    expect(document.diagnostics).toContainEqual({ path: "yarn.lock", reason: "parse_failed", detail, detector: "yarn-lock" });
    expect(document.categories.resolved_dependencies!.search.skipped).toEqual(["yarn.lock"]);
  });

  it("reports duplicate specifiers that resolve differently as a conflict", async () => {
    const { document } = await profile({
      "package.json": json({ name: "app", dependencies: { react: "^18.3.1" } }),
      "yarn.lock": 'react@^18.3.1:\n  version "18.3.1"\n\nreact@^18.3.1:\n  version "18.2.0"\n',
    });
    expect(resolved(document)).toEqual({ "package.json#react": ["18.2.0", "18.3.1"] });
    expect(facts(document)[0]!.state).toBe("conflicting");
  });

  it("uses the nearest lockfile for a nested project", async () => {
    const { document } = await profile({
      "package.json": json({ name: "root", dependencies: { react: "^18.3.1" } }),
      "yarn.lock": 'react@^18.3.1:\n  version "18.3.1"\n',
      "tools/cli/package.json": json({ name: "cli", dependencies: { react: "^18.3.1" } }),
      "tools/cli/yarn.lock": 'react@^18.3.1:\n  version "18.2.0"\n',
    });
    expect(resolved(document)).toEqual({ "package.json#react": "18.3.1", "tools/cli/package.json#react": "18.2.0" });
  });
});

describe("disagreeing lockfiles", () => {
  const FILES: FileTree = {
    "package.json": json({ name: "app", dependencies: { react: "^18.3.1" } }),
    "pnpm-lock.yaml": "lockfileVersion: '9.0'\nimporters:\n  .:\n    dependencies:\n      react:\n        specifier: ^18.3.1\n        version: 18.3.1\n",
    "yarn.lock": 'react@^18.3.1:\n  version "18.2.0"\n',
  };

  it("keeps both resolutions and their evidence as a conflict", async () => {
    const { document } = await profile(FILES);
    const react = facts(document).find((fact) => fact.key === "package.json#react")!;
    expect(react.state).toBe("conflicting");
    expect(react.value).toBeNull();
    expect(react.candidates!.map((candidate) => [(candidate.value as { version: string }).version, candidate.rule, candidate.evidence.map((id) => document.evidence[id]!.path)])).toEqual([
      ["18.2.0", "yarn-lock.resolved-version", ["yarn.lock"]],
      ["18.3.1", "pnpm-lock.resolved-version", ["pnpm-lock.yaml"]],
    ]);
    expect(document.categories.package_managers!.facts[0]).toMatchObject({ state: "conflicting" });
  });

  it("produces the same document on every run", async () => {
    expect(dump((await profile(FILES)).document)).toBe(dump((await profile(FILES)).document));
  });
});
