import fs from "node:fs";
import path from "node:path";
import { compileCatalogs } from "@repo-facts/design-system";
import { compileRules } from "@repo-facts/syntax";
import { describe, expect, it } from "vitest";

const ROOT = path.resolve(import.meta.dirname, "../..");
// Generated modules change only through `npm run rules:compile`, which sets this flag.
const UPDATE = process.env.REPO_FACTS_UPDATE_RULES === "1";
const RULE_PACKAGES = ["architecture", "services"];

/** The committed module a package's rules compile to. */
function generated(name: string, rules: unknown, digest: string): string {
  return [
    `// Generated by \`npm run rules:compile\` from packages/${name}/rules/*.yaml. Do not edit.`,
    'import type { Rule } from "@repo-facts/syntax";',
    "",
    `export const RULES: readonly Rule[] = ${JSON.stringify(rules, null, 2)};`,
    "",
    `export const RULES_DIGEST = ${JSON.stringify(digest)};`,
    "",
  ].join("\n");
}

/** The committed module the design-system catalogs compile to. */
function generatedCatalogs(catalogs: unknown, adapters: unknown, digest: string): string {
  return [
    "// Generated by `npm run rules:compile` from packages/design-system/catalogs/*.yaml. Do not edit.",
    'import type { AdapterCatalog, Catalog } from "./catalog-schema.js";',
    "",
    `export const CATALOGS: readonly Catalog[] = ${JSON.stringify(catalogs, null, 2)};`,
    "",
    `export const ADAPTERS: AdapterCatalog = ${JSON.stringify(adapters, null, 2)};`,
    "",
    `export const CATALOGS_DIGEST = ${JSON.stringify(digest)};`,
    "",
  ].join("\n");
}

describe("compiled syntax rules", () => {
  for (const name of RULE_PACKAGES) {
    it(`packages/${name}/src/rules.generated.ts matches its rule files`, () => {
      const directory = path.join(ROOT, "packages", name, "rules");
      const files = fs.existsSync(directory) ? fs.readdirSync(directory).filter((file) => file.endsWith(".yaml")) : [];
      const result = compileRules(files.map((file) => ({ path: `packages/${name}/rules/${file}`, text: fs.readFileSync(path.join(directory, file), "utf8") })));
      if (!result.ok) throw new Error(`Rules do not compile:\n${result.problems.join("\n")}`);
      const text = generated(name, result.rules, result.digest);
      const target = path.join(ROOT, "packages", name, "src", "rules.generated.ts");
      if (UPDATE) fs.writeFileSync(target, text);
      expect(fs.existsSync(target), `${target} is missing; run npm run rules:compile`).toBe(true);
      expect(fs.readFileSync(target, "utf8")).toBe(text);
    });
  }
});

describe("compiled design-system catalogs", () => {
  it("packages/design-system/src/catalogs.generated.ts matches its catalog files", () => {
    const directory = path.join(ROOT, "packages/design-system/catalogs");
    const read = (file: string) => ({ path: `packages/design-system/catalogs/${file}`, text: fs.readFileSync(path.join(directory, file), "utf8") });
    const files = fs.readdirSync(directory).filter((file) => file.endsWith(".yaml"));
    const result = compileCatalogs({ catalogs: files.filter((file) => file !== "adapters.yaml").map(read), adapters: read("adapters.yaml") });
    if (!result.ok) throw new Error(`Catalogs do not compile:\n${result.problems.join("\n")}`);
    const text = generatedCatalogs(result.catalogs, result.adapters, result.digest);
    const target = path.join(ROOT, "packages/design-system/src/catalogs.generated.ts");
    if (UPDATE) fs.writeFileSync(target, text);
    expect(fs.existsSync(target), `${target} is missing; run npm run rules:compile`).toBe(true);
    expect(fs.readFileSync(target, "utf8")).toBe(text);
  });
});
