// Generated by `npm run rules:compile` from packages/architecture/rules/*.yaml. Do not edit.
import type { Rule } from "@repo-facts/syntax";

export const RULES: readonly Rule[] = [];

export const RULES_DIGEST = "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945";
