// Generated by `npm run rules:compile` from packages/architecture/rules/*.yaml. Do not edit.
import type { Rule } from "@repo-facts/syntax";

export const RULES: readonly Rule[] = [
  {
    "capture": {
      "src": {
        "attribute": "src"
      }
    },
    "description": "An embedded frame and the address it loads",
    "emit": {
      "fact": {
        "basis": "observed",
        "category": "composition",
        "key": "iframe:{src}",
        "value": {
          "mechanism": "iframe",
          "src": "$src"
        }
      }
    },
    "id": "architecture.iframe.embed",
    "match": {
      "jsx": {
        "element": [
          "iframe"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "src": {
        "attribute": "src"
      }
    },
    "description": "An embedded frame, as a reference to the application it loads",
    "emit": {
      "reference": {
        "basis": "observed",
        "identifier": {
          "url": "{src}"
        },
        "role": "embedder",
        "type": "iframe"
      }
    },
    "id": "architecture.iframe.reference",
    "match": {
      "jsx": {
        "element": [
          "iframe"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "exposes": {
        "argument": 0,
        "property": [
          "exposes"
        ]
      },
      "name": {
        "argument": 0,
        "property": [
          "name"
        ]
      },
      "remotes": {
        "argument": 0,
        "property": [
          "remotes"
        ]
      },
      "shared": {
        "argument": 0,
        "property": [
          "shared"
        ]
      }
    },
    "description": "The Module Federation 2 plugin for webpack and Rspack",
    "emit": {
      "signal": {
        "kind": "module-federation"
      }
    },
    "id": "architecture.module-federation.enhanced",
    "match": {
      "new": {
        "members": [
          "ModuleFederationPlugin"
        ],
        "module": [
          "@module-federation/enhanced",
          "@module-federation/enhanced/webpack",
          "@module-federation/enhanced/rspack"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "exposes": {
        "argument": 0,
        "property": [
          "exposes"
        ]
      },
      "name": {
        "argument": 0,
        "property": [
          "name"
        ]
      },
      "remotes": {
        "argument": 0,
        "property": [
          "remotes"
        ]
      },
      "shared": {
        "argument": 0,
        "property": [
          "shared"
        ]
      }
    },
    "description": "Rspack's Module Federation plugins",
    "emit": {
      "signal": {
        "kind": "module-federation"
      }
    },
    "id": "architecture.module-federation.rspack",
    "match": {
      "new": {
        "members": [
          "container"
        ],
        "method": [
          "ModuleFederationPlugin",
          "ModuleFederationPluginV1"
        ],
        "module": [
          "@rspack/core"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "exposes": {
        "argument": 0,
        "property": [
          "exposes"
        ]
      },
      "name": {
        "argument": 0,
        "property": [
          "name"
        ]
      },
      "remotes": {
        "argument": 0,
        "property": [
          "remotes"
        ]
      },
      "shared": {
        "argument": 0,
        "property": [
          "shared"
        ]
      }
    },
    "description": "Module Federation plugins for Vite",
    "emit": {
      "signal": {
        "kind": "module-federation"
      }
    },
    "id": "architecture.module-federation.vite",
    "match": {
      "call": {
        "module": [
          "@originjs/vite-plugin-federation",
          "@module-federation/vite"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "exposes": {
        "argument": 0,
        "property": [
          "exposes"
        ]
      },
      "name": {
        "argument": 0,
        "property": [
          "name"
        ]
      },
      "remotes": {
        "argument": 0,
        "property": [
          "remotes"
        ]
      },
      "shared": {
        "argument": 0,
        "property": [
          "shared"
        ]
      }
    },
    "description": "The named federation export of @module-federation/vite",
    "emit": {
      "signal": {
        "kind": "module-federation"
      }
    },
    "id": "architecture.module-federation.vite-named",
    "match": {
      "call": {
        "members": [
          "federation"
        ],
        "module": [
          "@module-federation/vite"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "exposes": {
        "argument": 0,
        "property": [
          "exposes"
        ]
      },
      "name": {
        "argument": 0,
        "property": [
          "name"
        ]
      },
      "remotes": {
        "argument": 0,
        "property": [
          "remotes"
        ]
      },
      "shared": {
        "argument": 0,
        "property": [
          "shared"
        ]
      }
    },
    "description": "webpack's Module Federation plugin",
    "emit": {
      "signal": {
        "kind": "module-federation"
      }
    },
    "id": "architecture.module-federation.webpack",
    "match": {
      "new": {
        "members": [
          "container"
        ],
        "method": [
          "ModuleFederationPlugin"
        ],
        "module": [
          "webpack"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "event": {
        "argument": 0
      }
    },
    "description": "A listener for window messages",
    "emit": {
      "fact": {
        "basis": "observed",
        "category": "runtime_integrations",
        "key": "postMessage:receive",
        "value": {
          "contract": "postMessage",
          "direction": "receive"
        }
      }
    },
    "id": "architecture.post-message.receive",
    "match": {
      "call": {
        "anyReceiver": true,
        "method": [
          "addEventListener"
        ]
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "event",
        "equals": "message"
      }
    ]
  },
  {
    "capture": {
      "origin": {
        "argument": 1
      }
    },
    "description": "A window message sent to a literal origin, as a runtime-contract reference",
    "emit": {
      "reference": {
        "basis": "observed",
        "identifier": {
          "contract": "postMessage",
          "origin": "{origin}"
        },
        "role": "caller",
        "type": "runtime_contract"
      }
    },
    "id": "architecture.post-message.reference",
    "match": {
      "call": {
        "anyReceiver": true,
        "method": [
          "postMessage"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "message": {
        "argument": 0
      },
      "origin": {
        "argument": 1
      }
    },
    "description": "A window message sent to another frame",
    "emit": {
      "fact": {
        "basis": "observed",
        "category": "runtime_integrations",
        "key": "postMessage:send:{origin}",
        "value": {
          "contract": "postMessage",
          "direction": "send",
          "message": "$message",
          "targetOrigin": "$origin"
        }
      }
    },
    "id": "architecture.post-message.send",
    "match": {
      "call": {
        "anyReceiver": true,
        "method": [
          "postMessage"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "helper": {
        "argument": 0
      }
    },
    "description": "Lifecycles produced by a single-spa framework helper",
    "emit": {
      "signal": {
        "kind": "single-spa-lifecycles"
      }
    },
    "id": "architecture.single-spa.lifecycles",
    "match": {
      "call": {
        "module": [
          "single-spa-react",
          "single-spa-vue",
          "single-spa-angular",
          "single-spa-svelte",
          "single-spa-html"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "activeWhen": {
        "argument": 0,
        "property": [
          "activeWhen"
        ]
      },
      "config": {
        "argument": 0
      },
      "name": {
        "argument": 0,
        "property": [
          "name"
        ]
      }
    },
    "description": "A single-spa application registered with a configuration object",
    "emit": {
      "fact": {
        "basis": "observed",
        "category": "composition",
        "key": "single-spa:application:{name}",
        "value": {
          "activeWhen": "$activeWhen",
          "application": "$name",
          "mechanism": "single-spa",
          "role": "registration"
        }
      }
    },
    "id": "architecture.single-spa.register",
    "match": {
      "call": {
        "members": [
          "registerApplication"
        ],
        "module": [
          "single-spa"
        ]
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "config",
        "is": [
          "object"
        ]
      }
    ]
  },
  {
    "capture": {
      "activeWhen": {
        "argument": 2
      },
      "name": {
        "argument": 0
      }
    },
    "description": "A single-spa application registered with positional arguments",
    "emit": {
      "fact": {
        "basis": "observed",
        "category": "composition",
        "key": "single-spa:application:{name}",
        "value": {
          "activeWhen": "$activeWhen",
          "application": "$name",
          "mechanism": "single-spa",
          "role": "registration"
        }
      }
    },
    "id": "architecture.single-spa.register-positional",
    "match": {
      "call": {
        "members": [
          "registerApplication"
        ],
        "module": [
          "single-spa"
        ]
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "name",
        "is": [
          "string"
        ]
      }
    ]
  },
  {
    "capture": {
      "name": {
        "argument": 0
      }
    },
    "description": "A positionally registered single-spa application, as a reference to the repository that provides it",
    "emit": {
      "reference": {
        "basis": "observed",
        "identifier": {
          "application": "{name}",
          "mechanism": "single-spa"
        },
        "role": "host",
        "type": "composition"
      }
    },
    "id": "architecture.single-spa.register-positional-reference",
    "match": {
      "call": {
        "members": [
          "registerApplication"
        ],
        "module": [
          "single-spa"
        ]
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "name",
        "is": [
          "string"
        ]
      }
    ]
  },
  {
    "capture": {
      "config": {
        "argument": 0
      },
      "name": {
        "argument": 0,
        "property": [
          "name"
        ]
      }
    },
    "description": "A registered single-spa application, as a reference to the repository that provides it",
    "emit": {
      "reference": {
        "basis": "observed",
        "identifier": {
          "application": "{name}",
          "mechanism": "single-spa"
        },
        "role": "host",
        "type": "composition"
      }
    },
    "id": "architecture.single-spa.register-reference",
    "match": {
      "call": {
        "members": [
          "registerApplication"
        ],
        "module": [
          "single-spa"
        ]
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "config",
        "is": [
          "object"
        ]
      }
    ]
  },
  {
    "description": "single-spa started by a root configuration",
    "emit": {
      "signal": {
        "kind": "single-spa-start"
      }
    },
    "id": "architecture.single-spa.start",
    "match": {
      "call": {
        "members": [
          "start"
        ],
        "module": [
          "single-spa"
        ]
      }
    },
    "version": 1
  }
];

export const RULES_DIGEST = "2d959b575d3c6a2a6ce0408f302c04b358e2385f668f8e849d03a26275f812cf";
