// Generated by `npm run rules:compile` from packages/services/rules/*.yaml. Do not edit.
import type { Rule } from "@repo-facts/syntax";

export const RULES: readonly Rule[] = [
  {
    "capture": {
      "module": {
        "module": true
      }
    },
    "description": "An authentication library",
    "emit": {
      "signal": {
        "kind": "auth-library"
      }
    },
    "id": "services.access.auth-library",
    "match": {
      "import": {
        "module": [
          "@azure/msal-browser",
          "@azure/msal-react",
          "@azure/msal-node",
          "oidc-client-ts",
          "oidc-client",
          "keycloak-js",
          "next-auth",
          "next-auth/react",
          "@auth0/auth0-react",
          "@auth0/auth0-spa-js",
          "@okta/okta-auth-js",
          "@okta/okta-react",
          "firebase/auth",
          "aws-amplify",
          "@aws-amplify/auth"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "options": {
        "argument": 1
      },
      "retries": {
        "argument": 1,
        "property": [
          "retries"
        ]
      }
    },
    "description": "Retries configured for an axios instance with axios-retry",
    "emit": {
      "signal": {
        "kind": "axios-retry"
      }
    },
    "id": "services.axios-retry",
    "match": {
      "call": {
        "module": [
          "axios-retry"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "baseURL": {
        "argument": 0,
        "property": [
          "baseURL"
        ]
      },
      "config": {
        "argument": 0
      },
      "data": {
        "argument": 0,
        "property": [
          "data"
        ]
      },
      "headers": {
        "argument": 0,
        "property": [
          "headers"
        ]
      },
      "requestMethod": {
        "argument": 0,
        "property": [
          "method"
        ]
      },
      "timeout": {
        "argument": 0,
        "property": [
          "timeout"
        ]
      },
      "url": {
        "argument": 0,
        "property": [
          "url"
        ]
      }
    },
    "description": "A request made by calling axios with a configuration object",
    "emit": {
      "service": {
        "client": "axios",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.axios.config-call",
    "match": {
      "call": {
        "module": [
          "axios"
        ]
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "config",
        "is": [
          "object"
        ]
      }
    ]
  },
  {
    "capture": {
      "baseURL": {
        "argument": 0,
        "property": [
          "baseURL"
        ]
      },
      "config": {
        "argument": 0
      },
      "headers": {
        "argument": 0,
        "property": [
          "headers"
        ]
      },
      "timeout": {
        "argument": 0,
        "property": [
          "timeout"
        ]
      }
    },
    "description": "A configured axios instance",
    "emit": {
      "signal": {
        "kind": "axios-instance"
      }
    },
    "id": "services.axios.create",
    "match": {
      "call": {
        "method": [
          "create"
        ],
        "module": [
          "axios"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "config": {
        "argument": 1
      },
      "headers": {
        "argument": 1,
        "property": [
          "headers"
        ]
      },
      "timeout": {
        "argument": 1,
        "property": [
          "timeout"
        ]
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A request without a body made through a configured axios instance",
    "emit": {
      "service": {
        "client": "axios",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.axios.instance-request",
    "match": {
      "call": {
        "instanceOf": "services.axios.create",
        "method": [
          "get",
          "delete",
          "head",
          "options"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "config": {
        "argument": 2
      },
      "data": {
        "argument": 1
      },
      "headers": {
        "argument": 2,
        "property": [
          "headers"
        ]
      },
      "timeout": {
        "argument": 2,
        "property": [
          "timeout"
        ]
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A request with a body made through a configured axios instance",
    "emit": {
      "service": {
        "client": "axios",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.axios.instance-request-with-data",
    "match": {
      "call": {
        "instanceOf": "services.axios.create",
        "method": [
          "post",
          "put",
          "patch"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "config": {
        "argument": 1
      },
      "headers": {
        "argument": 1,
        "property": [
          "headers"
        ]
      },
      "timeout": {
        "argument": 1,
        "property": [
          "timeout"
        ]
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A request without a body made with axios",
    "emit": {
      "service": {
        "client": "axios",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.axios.request",
    "match": {
      "call": {
        "method": [
          "get",
          "delete",
          "head",
          "options"
        ],
        "module": [
          "axios"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "config": {
        "argument": 2
      },
      "data": {
        "argument": 1
      },
      "headers": {
        "argument": 2,
        "property": [
          "headers"
        ]
      },
      "timeout": {
        "argument": 2,
        "property": [
          "timeout"
        ]
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A request with a body made with axios",
    "emit": {
      "service": {
        "client": "axios",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.axios.request-with-data",
    "match": {
      "call": {
        "method": [
          "post",
          "put",
          "patch"
        ],
        "module": [
          "axios"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "first": {
        "argument": 0
      },
      "options": {
        "argument": 1
      }
    },
    "description": "A route proxied with http-proxy-middleware",
    "emit": {
      "signal": {
        "kind": "proxy-middleware"
      }
    },
    "id": "services.egress.proxy-middleware",
    "match": {
      "call": {
        "members": [
          "createProxyMiddleware"
        ],
        "module": [
          "http-proxy-middleware"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "proxy": {
        "argument": 0,
        "property": [
          "server",
          "proxy"
        ]
      }
    },
    "description": "Development proxy routes in a Vite configuration",
    "emit": {
      "signal": {
        "kind": "dev-proxy"
      }
    },
    "id": "services.egress.vite-proxy",
    "match": {
      "call": {
        "members": [
          "defineConfig"
        ],
        "module": [
          "vite"
        ]
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "proxy",
        "is": [
          "object",
          "unresolved"
        ]
      }
    ]
  },
  {
    "capture": {
      "credentials": {
        "argument": 1,
        "property": [
          "withCredentials"
        ]
      },
      "init": {
        "argument": 1
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A server-sent events stream",
    "emit": {
      "service": {
        "client": "event_source",
        "facts": {
          "protocol": {
            "literal": "sse"
          }
        }
      }
    },
    "id": "services.event-source",
    "match": {
      "new": {
        "global": "EventSource"
      }
    },
    "version": 1
  },
  {
    "capture": {
      "credentials": {
        "argument": 1,
        "property": [
          "credentials"
        ]
      },
      "headers": {
        "argument": 1,
        "property": [
          "headers"
        ]
      },
      "init": {
        "argument": 1
      },
      "requestMethod": {
        "argument": 1,
        "property": [
          "method"
        ]
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A request made with fetch",
    "emit": {
      "service": {
        "client": "fetch",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.fetch",
    "match": {
      "call": {
        "global": "fetch"
      }
    },
    "version": 1
  },
  {
    "capture": {
      "baseURL": {
        "argument": 0,
        "property": [
          "baseUrl"
        ]
      },
      "config": {
        "argument": 0
      },
      "headers": {
        "argument": 0,
        "property": [
          "headers"
        ]
      }
    },
    "description": "A client generated from an OpenAPI document with openapi-fetch",
    "emit": {
      "signal": {
        "kind": "generated-client"
      }
    },
    "id": "services.generated.openapi-fetch",
    "match": {
      "call": {
        "module": [
          "openapi-fetch",
          "@hey-api/client-fetch"
        ]
      }
    },
    "version": 2,
    "where": [
      {
        "capture": "config",
        "is": [
          "object"
        ]
      }
    ]
  },
  {
    "capture": {
      "data": {
        "argument": 1,
        "property": [
          "body"
        ]
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A request made through an openapi-fetch client",
    "emit": {
      "service": {
        "client": "generated",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.generated.openapi-fetch-request",
    "match": {
      "call": {
        "instanceOf": "services.generated.openapi-fetch",
        "method": [
          "GET",
          "POST",
          "PUT",
          "PATCH",
          "DELETE",
          "HEAD",
          "OPTIONS"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "headers": {
        "argument": 0,
        "property": [
          "headers"
        ]
      },
      "url": {
        "argument": 0,
        "property": [
          "uri"
        ]
      }
    },
    "description": "An Apollo GraphQL client or link with its endpoint",
    "emit": {
      "service": {
        "client": "graphql",
        "facts": {
          "protocol": {
            "literal": "graphql"
          }
        }
      }
    },
    "id": "services.graphql.apollo",
    "match": {
      "new": {
        "method": [
          "ApolloClient",
          "HttpLink"
        ],
        "module": [
          "@apollo/client"
        ]
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "url",
        "is": [
          "string",
          "template",
          "configured",
          "unresolved"
        ]
      }
    ]
  },
  {
    "capture": {
      "document": {
        "template": true
      }
    },
    "description": "A GraphQL document written with Apollo's gql",
    "emit": {
      "signal": {
        "kind": "graphql-document"
      }
    },
    "id": "services.graphql.document-apollo",
    "match": {
      "tagged": {
        "members": [
          "gql"
        ],
        "module": [
          "@apollo/client",
          "@apollo/client/core"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "document": {
        "template": true
      }
    },
    "description": "A GraphQL document written with graphql-tag",
    "emit": {
      "signal": {
        "kind": "graphql-document"
      }
    },
    "id": "services.graphql.document-tag",
    "match": {
      "tagged": {
        "module": [
          "graphql-tag"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "document": {
        "argument": 1
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A single graphql-request request",
    "emit": {
      "service": {
        "client": "graphql",
        "facts": {
          "protocol": {
            "literal": "graphql"
          }
        }
      }
    },
    "id": "services.graphql.request",
    "match": {
      "call": {
        "members": [
          "request"
        ],
        "module": [
          "graphql-request"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "headers": {
        "argument": 1,
        "property": [
          "headers"
        ]
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A graphql-request client",
    "emit": {
      "service": {
        "client": "graphql",
        "facts": {
          "protocol": {
            "literal": "graphql"
          }
        }
      }
    },
    "id": "services.graphql.request-client",
    "match": {
      "new": {
        "members": [
          "GraphQLClient"
        ],
        "module": [
          "graphql-request"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "url": {
        "argument": 0,
        "firstOf": [
          "endpoint",
          "baseURL",
          "baseUrl",
          "apiUrl",
          "apiBaseUrl",
          "uri",
          "url"
        ]
      }
    },
    "description": "A packaged service client configured with an endpoint by a call to its export",
    "emit": {
      "service": {
        "client": "packaged",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.packaged.configure",
    "match": {
      "call": {
        "anyModule": true
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "url",
        "is": [
          "string",
          "template",
          "configured"
        ]
      }
    ]
  },
  {
    "capture": {
      "module": {
        "argument": 0
      }
    },
    "description": "A module replaced with a global vi.mock or jest.mock",
    "emit": {
      "signal": {
        "kind": "module-mock-candidate"
      }
    },
    "id": "services.substitute.global-module-mock",
    "match": {
      "call": {
        "anyReceiver": true,
        "method": [
          "mock",
          "doMock"
        ]
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "module",
        "is": [
          "string"
        ]
      }
    ]
  },
  {
    "capture": {
      "name": {
        "argument": 1
      }
    },
    "description": "The global fetch replaced with jest.spyOn or vi.spyOn",
    "emit": {
      "signal": {
        "kind": "fetch-stub"
      }
    },
    "id": "services.substitute.jest-spy-fetch",
    "match": {
      "call": {
        "anyReceiver": true,
        "method": [
          "spyOn"
        ]
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "name",
        "equals": "fetch"
      }
    ]
  },
  {
    "capture": {
      "module": {
        "module": true
      }
    },
    "description": "A mock server library",
    "emit": {
      "signal": {
        "kind": "mock-server"
      }
    },
    "id": "services.substitute.mock-server-library",
    "match": {
      "import": {
        "module": [
          "miragejs",
          "json-server",
          "@mswjs/data",
          "pretender"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "operation": {
        "argument": 0
      }
    },
    "description": "A Mock Service Worker GraphQL operation handler",
    "emit": {
      "signal": {
        "kind": "graphql-interceptor"
      }
    },
    "id": "services.substitute.msw-graphql-handler",
    "match": {
      "call": {
        "members": [
          "graphql"
        ],
        "method": [
          "query",
          "mutation",
          "operation"
        ],
        "module": [
          "msw"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "url": {
        "argument": 0
      }
    },
    "description": "A Mock Service Worker request handler",
    "emit": {
      "signal": {
        "kind": "request-interceptor"
      }
    },
    "id": "services.substitute.msw-handler",
    "match": {
      "call": {
        "members": [
          "http"
        ],
        "method": [
          "get",
          "post",
          "put",
          "patch",
          "delete",
          "head",
          "options",
          "all"
        ],
        "module": [
          "msw"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "url": {
        "argument": 0
      }
    },
    "description": "A Mock Service Worker request handler written with the legacy rest namespace",
    "emit": {
      "signal": {
        "kind": "request-interceptor"
      }
    },
    "id": "services.substitute.msw-rest-handler",
    "match": {
      "call": {
        "members": [
          "rest"
        ],
        "method": [
          "get",
          "post",
          "put",
          "patch",
          "delete",
          "head",
          "options",
          "all"
        ],
        "module": [
          "msw"
        ]
      }
    },
    "version": 1
  },
  {
    "description": "A Mock Service Worker server or worker",
    "emit": {
      "signal": {
        "kind": "mock-server"
      }
    },
    "id": "services.substitute.msw-server",
    "match": {
      "call": {
        "method": [
          "setupServer",
          "setupWorker"
        ],
        "module": [
          "msw",
          "msw/node",
          "msw/browser"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "url": {
        "argument": 0
      }
    },
    "description": "A nock interceptor for an origin",
    "emit": {
      "signal": {
        "kind": "request-interceptor"
      }
    },
    "id": "services.substitute.nock",
    "match": {
      "call": {
        "module": [
          "nock"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "module": {
        "argument": 0
      }
    },
    "description": "A module replaced with vi.mock",
    "emit": {
      "signal": {
        "kind": "module-mock"
      }
    },
    "id": "services.substitute.vitest-module-mock",
    "match": {
      "call": {
        "members": [
          "vi"
        ],
        "method": [
          "mock",
          "doMock"
        ],
        "module": [
          "vitest"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "name": {
        "argument": 0
      }
    },
    "description": "A global replaced with vi.stubGlobal",
    "emit": {
      "signal": {
        "kind": "fetch-stub"
      }
    },
    "id": "services.substitute.vitest-stub-global",
    "match": {
      "call": {
        "anyReceiver": true,
        "method": [
          "stubGlobal"
        ]
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "name",
        "equals": "fetch"
      }
    ]
  },
  {
    "capture": {
      "url": {
        "argument": 0
      }
    },
    "description": "A WebSocket connection",
    "emit": {
      "service": {
        "client": "websocket",
        "facts": {
          "protocol": {
            "literal": "websocket"
          }
        }
      }
    },
    "id": "services.websocket",
    "match": {
      "new": {
        "global": "WebSocket"
      }
    },
    "version": 1
  }
];

export const RULES_DIGEST = "112f81bdb910917eeace94f63a54d8425ce4bf6fa283af50e65ff0cccf09dd4f";
