// Generated by `npm run rules:compile` from packages/services/rules/*.yaml. Do not edit.
import type { Rule } from "@repo-facts/syntax";

export const RULES: readonly Rule[] = [
  {
    "capture": {
      "options": {
        "argument": 1
      },
      "retries": {
        "argument": 1,
        "property": [
          "retries"
        ]
      }
    },
    "description": "Retries configured for an axios instance with axios-retry",
    "emit": {
      "signal": {
        "kind": "axios-retry"
      }
    },
    "id": "services.axios-retry",
    "match": {
      "call": {
        "module": [
          "axios-retry"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "baseURL": {
        "argument": 0,
        "property": [
          "baseURL"
        ]
      },
      "config": {
        "argument": 0
      },
      "data": {
        "argument": 0,
        "property": [
          "data"
        ]
      },
      "headers": {
        "argument": 0,
        "property": [
          "headers"
        ]
      },
      "requestMethod": {
        "argument": 0,
        "property": [
          "method"
        ]
      },
      "timeout": {
        "argument": 0,
        "property": [
          "timeout"
        ]
      },
      "url": {
        "argument": 0,
        "property": [
          "url"
        ]
      }
    },
    "description": "A request made by calling axios with a configuration object",
    "emit": {
      "service": {
        "client": "axios",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.axios.config-call",
    "match": {
      "call": {
        "module": [
          "axios"
        ]
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "config",
        "is": [
          "object"
        ]
      }
    ]
  },
  {
    "capture": {
      "baseURL": {
        "argument": 0,
        "property": [
          "baseURL"
        ]
      },
      "config": {
        "argument": 0
      },
      "headers": {
        "argument": 0,
        "property": [
          "headers"
        ]
      },
      "timeout": {
        "argument": 0,
        "property": [
          "timeout"
        ]
      }
    },
    "description": "A configured axios instance",
    "emit": {
      "signal": {
        "kind": "axios-instance"
      }
    },
    "id": "services.axios.create",
    "match": {
      "call": {
        "method": [
          "create"
        ],
        "module": [
          "axios"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "config": {
        "argument": 1
      },
      "headers": {
        "argument": 1,
        "property": [
          "headers"
        ]
      },
      "timeout": {
        "argument": 1,
        "property": [
          "timeout"
        ]
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A request without a body made through a configured axios instance",
    "emit": {
      "service": {
        "client": "axios",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.axios.instance-request",
    "match": {
      "call": {
        "instanceOf": "services.axios.create",
        "method": [
          "get",
          "delete",
          "head",
          "options"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "config": {
        "argument": 2
      },
      "data": {
        "argument": 1
      },
      "headers": {
        "argument": 2,
        "property": [
          "headers"
        ]
      },
      "timeout": {
        "argument": 2,
        "property": [
          "timeout"
        ]
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A request with a body made through a configured axios instance",
    "emit": {
      "service": {
        "client": "axios",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.axios.instance-request-with-data",
    "match": {
      "call": {
        "instanceOf": "services.axios.create",
        "method": [
          "post",
          "put",
          "patch"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "config": {
        "argument": 1
      },
      "headers": {
        "argument": 1,
        "property": [
          "headers"
        ]
      },
      "timeout": {
        "argument": 1,
        "property": [
          "timeout"
        ]
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A request without a body made with axios",
    "emit": {
      "service": {
        "client": "axios",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.axios.request",
    "match": {
      "call": {
        "method": [
          "get",
          "delete",
          "head",
          "options"
        ],
        "module": [
          "axios"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "config": {
        "argument": 2
      },
      "data": {
        "argument": 1
      },
      "headers": {
        "argument": 2,
        "property": [
          "headers"
        ]
      },
      "timeout": {
        "argument": 2,
        "property": [
          "timeout"
        ]
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A request with a body made with axios",
    "emit": {
      "service": {
        "client": "axios",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.axios.request-with-data",
    "match": {
      "call": {
        "method": [
          "post",
          "put",
          "patch"
        ],
        "module": [
          "axios"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "credentials": {
        "argument": 1,
        "property": [
          "withCredentials"
        ]
      },
      "init": {
        "argument": 1
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A server-sent events stream",
    "emit": {
      "service": {
        "client": "event_source",
        "facts": {
          "protocol": {
            "literal": "sse"
          }
        }
      }
    },
    "id": "services.event-source",
    "match": {
      "new": {
        "global": "EventSource"
      }
    },
    "version": 1
  },
  {
    "capture": {
      "credentials": {
        "argument": 1,
        "property": [
          "credentials"
        ]
      },
      "headers": {
        "argument": 1,
        "property": [
          "headers"
        ]
      },
      "init": {
        "argument": 1
      },
      "requestMethod": {
        "argument": 1,
        "property": [
          "method"
        ]
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A request made with fetch",
    "emit": {
      "service": {
        "client": "fetch",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.fetch",
    "match": {
      "call": {
        "global": "fetch"
      }
    },
    "version": 1
  },
  {
    "capture": {
      "baseURL": {
        "argument": 0,
        "property": [
          "baseUrl"
        ]
      },
      "config": {
        "argument": 0
      }
    },
    "description": "A client generated from an OpenAPI document with openapi-fetch",
    "emit": {
      "signal": {
        "kind": "generated-client"
      }
    },
    "id": "services.generated.openapi-fetch",
    "match": {
      "call": {
        "module": [
          "openapi-fetch",
          "@hey-api/client-fetch"
        ]
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "config",
        "is": [
          "object"
        ]
      }
    ]
  },
  {
    "capture": {
      "data": {
        "argument": 1,
        "property": [
          "body"
        ]
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A request made through an openapi-fetch client",
    "emit": {
      "service": {
        "client": "generated",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.generated.openapi-fetch-request",
    "match": {
      "call": {
        "instanceOf": "services.generated.openapi-fetch",
        "method": [
          "GET",
          "POST",
          "PUT",
          "PATCH",
          "DELETE",
          "HEAD",
          "OPTIONS"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "headers": {
        "argument": 0,
        "property": [
          "headers"
        ]
      },
      "url": {
        "argument": 0,
        "property": [
          "uri"
        ]
      }
    },
    "description": "An Apollo GraphQL client or link with its endpoint",
    "emit": {
      "service": {
        "client": "graphql",
        "facts": {
          "protocol": {
            "literal": "graphql"
          }
        }
      }
    },
    "id": "services.graphql.apollo",
    "match": {
      "new": {
        "method": [
          "ApolloClient",
          "HttpLink"
        ],
        "module": [
          "@apollo/client"
        ]
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "url",
        "is": [
          "string",
          "template",
          "configured",
          "unresolved"
        ]
      }
    ]
  },
  {
    "capture": {
      "document": {
        "template": true
      }
    },
    "description": "A GraphQL document written with Apollo's gql",
    "emit": {
      "signal": {
        "kind": "graphql-document"
      }
    },
    "id": "services.graphql.document-apollo",
    "match": {
      "tagged": {
        "members": [
          "gql"
        ],
        "module": [
          "@apollo/client",
          "@apollo/client/core"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "document": {
        "template": true
      }
    },
    "description": "A GraphQL document written with graphql-tag",
    "emit": {
      "signal": {
        "kind": "graphql-document"
      }
    },
    "id": "services.graphql.document-tag",
    "match": {
      "tagged": {
        "module": [
          "graphql-tag"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "document": {
        "argument": 1
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A single graphql-request request",
    "emit": {
      "service": {
        "client": "graphql",
        "facts": {
          "protocol": {
            "literal": "graphql"
          }
        }
      }
    },
    "id": "services.graphql.request",
    "match": {
      "call": {
        "members": [
          "request"
        ],
        "module": [
          "graphql-request"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "headers": {
        "argument": 1,
        "property": [
          "headers"
        ]
      },
      "url": {
        "argument": 0
      }
    },
    "description": "A graphql-request client",
    "emit": {
      "service": {
        "client": "graphql",
        "facts": {
          "protocol": {
            "literal": "graphql"
          }
        }
      }
    },
    "id": "services.graphql.request-client",
    "match": {
      "new": {
        "members": [
          "GraphQLClient"
        ],
        "module": [
          "graphql-request"
        ]
      }
    },
    "version": 1
  },
  {
    "capture": {
      "url": {
        "argument": 0,
        "firstOf": [
          "endpoint",
          "baseURL",
          "baseUrl",
          "apiUrl",
          "apiBaseUrl",
          "uri",
          "url"
        ]
      }
    },
    "description": "A packaged service client configured with an endpoint by a call to its export",
    "emit": {
      "service": {
        "client": "packaged",
        "facts": {
          "protocol": {
            "literal": "http"
          }
        }
      }
    },
    "id": "services.packaged.configure",
    "match": {
      "call": {
        "anyModule": true
      }
    },
    "version": 1,
    "where": [
      {
        "capture": "url",
        "is": [
          "string",
          "template",
          "configured"
        ]
      }
    ]
  },
  {
    "capture": {
      "url": {
        "argument": 0
      }
    },
    "description": "A WebSocket connection",
    "emit": {
      "service": {
        "client": "websocket",
        "facts": {
          "protocol": {
            "literal": "websocket"
          }
        }
      }
    },
    "id": "services.websocket",
    "match": {
      "new": {
        "global": "WebSocket"
      }
    },
    "version": 1
  }
];

export const RULES_DIGEST = "0914e04b05385aff6d48b2ce483535b56bfd6f21e49a45f8df8d2557742f4a5c";
