import { type Detector, type DetectorContext, type Evidence, type ServiceCandidate, type ServiceFactCandidate, type Value, compareCodeUnits, redactCredentials, sensitiveFormat } from "@repo-facts/contract";
import { inventoryOf, isVendored, readableInputs, unanalyzedInputs } from "@repo-facts/core";
import { type ConfigSource, type MatchedRule, type StaticValue, type SyntaxTree, captureValue, literalText, nodeEvidence, propertyName, syntaxOf, unwrap } from "@repo-facts/syntax";
import ts from "typescript";
import { SERVICE_MATCHES, SERVICE_SUMMARY, type ServiceSummary, deriveEndpoint, fromText } from "./services.js";

/**
 * Access and testability signals, never access itself.
 *
 * Credentials, certificates, proxies, and gateways are reported by the names
 * source reads them from, never by value; a credential file is reported only
 * as existing. Committed API contracts, generated schemas, and existing test
 * substitutes are tied to a Service Dependency only by evidence. For each
 * service, every candidate is tied (observed or inferred), still possible, or
 * excluded by evidence; "no contract" or "no detected substitute" is reported
 * only when the search was complete and every candidate is excluded. Nothing
 * here claims a substitute behaves like the service, and nothing is generated.
 */

const RULES = {
  environment: "access.environment-reference",
  dockerfile: "access.dockerfile-variable",
  credentialFile: "access.credential-file",
  networkZone: "access.network-zone",
  accessSearch: "access.search",
  gatewayFile: "egress.gateway-configuration-file",
  egressSearch: "egress.search",
  openapi: "contracts.openapi-document",
  graphql: "contracts.graphql-document",
  generatedSchema: "contracts.generated-schema",
  contractSearch: "contracts.search",
  fixture: "substitutes.fixture",
  substituteSearch: "substitutes.search",
  association: "services.evidence-association",
} as const;

type Classification = "credential_reference" | "certificate_reference" | "authentication_configuration" | "proxy_variable" | "gateway_configuration";

const CREDENTIAL_WORDS = new Set(["TOKEN", "SECRET", "PASSWORD", "PASSWD", "PASSPHRASE", "APIKEY", "CREDENTIAL", "CREDENTIALS", "BEARER", "JWT"]);
const KEY_QUALIFIERS = new Set(["API", "ACCESS", "PRIVATE", "SECRET", "CLIENT", "SIGNING"]);
const CERTIFICATE_WORDS = new Set(["CERT", "CERTS", "CERTIFICATE", "CA", "TLS", "SSL", "PFX", "KEYSTORE", "TRUSTSTORE"]);
const AUTHENTICATION_WORDS = new Set(["AUTH", "OAUTH", "OIDC", "SSO", "SAML", "AUTHORITY"]);
const FIXTURE_DIRECTORIES = new Set(["__fixtures__", "fixtures", "__mocks__", "mocks", "mock-data"]);
const MODULE_EXTENSIONS = ["", ".ts", ".tsx", ".d.ts", ".js", ".jsx", ".mjs", ".cjs", ".mts", ".cts", ".json"];
const GENERATED = /(auto-?generated|generated by|@generated|do not (edit|modify))/i;
const GENERATORS: readonly [RegExp, string, "openapi" | "graphql"][] = [
  [/openapi-typescript/i, "openapi-typescript", "openapi"],
  [/@hey-api\/openapi-ts/i, "@hey-api/openapi-ts", "openapi"],
  [/\borval\b/i, "orval", "openapi"],
  [/openapi[- ]generator/i, "openapi-generator", "openapi"],
  [/swagger-typescript-api/i, "swagger-typescript-api", "openapi"],
  [/graphql[- ]code[- ]?gen(erator)?/i, "graphql-codegen", "graphql"],
];
/** Reverse proxies and gateways recognized from the tree listing; the rules inside are not analyzed. */
const GATEWAY_FILES: readonly [(name: string) => boolean, string][] = [
  [(name) => name === "nginx.conf" || name.endsWith(".nginx.conf"), "nginx"],
  [(name) => name === "Caddyfile", "Caddy"],
  [(name) => /^traefik\.(ya?ml|toml)$/.test(name), "Traefik"],
  [(name) => /^kong\.ya?ml$/.test(name), "Kong"],
  [(name) => /^envoy\.ya?ml$/.test(name), "Envoy"],
  [(name) => name === "haproxy.cfg", "HAProxy"],
];
/** Packages a module mock replaces for each client kind. */
const CLIENT_PACKAGES: Partial<Record<ServiceSummary["client"], readonly string[]>> = {
  axios: ["axios"],
  graphql: ["graphql-request", "@apollo/client", "@apollo/client/core"],
  generated: ["openapi-fetch", "@hey-api/client-fetch"],
};

/** Clients that make their requests with the global fetch, and clients that never do. Others may. */
const FETCH_CLIENTS: ReadonlySet<ServiceSummary["client"]> = new Set(["fetch", "generated"]);
const NON_FETCH_CLIENTS: ReadonlySet<ServiceSummary["client"]> = new Set(["axios", "websocket", "event_source", "host_adapter"]);

/** How one candidate contract or substitute relates to one Service Dependency. */
type Relation = { tie: "observed"; association: string } | { tie: "inferred"; association: string; reasoning: string } | { tie: "possible" } | { tie: "excluded" };

interface Candidate {
  item: Record<string, Value>;
  evidence: Evidence;
  relation(summary: ServiceSummary): Relation;
}

type Tie = { candidate: Candidate; relation: Extract<Relation, { tie: "observed" | "inferred" }> };

interface Reference {
  name: string;
  source: ConfigSource | "Dockerfile";
  evidence: Evidence;
}

interface Route {
  route: string;
  target: Value;
  path: string;
  evidence: Evidence;
  rule: string;
}

export const serviceSignalsDetector: Detector = {
  id: "service-signals",
  version: "1",
  stage: "services",
  inputs: ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx", "**/*.mjs", "**/*.cjs", "**/Dockerfile", "**/*.graphql", "**/*.gql", "**/openapi.yaml", "**/openapi.json"],
  categories: ["access_signals", "egress_routes", "api_contracts", "test_substitutes"],
  async run(context) {
    const matches = context.shared.get(SERVICE_MATCHES) as MatchedRule[] | undefined;
    const summaries = context.shared.get(SERVICE_SUMMARY) as ServiceSummary[] | undefined;
    if (!matches || !summaries) throw new Error("The service-dependencies detector has not run");
    const signal = (kind: string) => matches.filter((match) => "signal" in match.rule.emit && match.rule.emit.signal.kind === kind);

    const sources = [...inventoryOf(context).sources];
    const trees = new Map<string, SyntaxTree>();
    const unparsed: string[] = [];
    for (const path of sources) {
      const tree = await syntaxOf(context, path);
      if (tree) trees.set(path, tree);
      else unparsed.push(path);
    }
    const imports = importGraph(context, trees);

    await reportAccess(context, [...trees.values()], signal, summaries, sources, unparsed);
    const routes = reportEgress(context, signal, sources, unparsed);
    const contracts = await reportContracts(context, [...trees.values()], imports, summaries, sources, unparsed);
    const substitutes = reportSubstitutes(context, signal, imports, summaries);
    context.search({ category: "test_substitutes", rule: RULES.substituteSearch, surface: sources, complete: true, skipped: unparsed });

    for (const summary of summaries) {
      const client = { kind: summary.client, package: summary.pkg };
      const facts: ServiceCandidate["facts"] = {};
      const extra: ServiceCandidate[] = [];

      // Several documents that could each be a service's contract compete; none is chosen.
      const contractTies = related(contracts.candidates, summary);
      if (contractTies.observed.length === 0 && contractTies.inferred.length > 1) {
        for (const tie of contractTies.inferred) extra.push({ key: summary.key, client, callSites: [], facts: { contracts: associate([tie]) } });
      } else {
        facts.contracts = serviceFact(contractTies, contracts.complete, contracts.surface, RULES.contractSearch, "No committed contract is tied to this service by evidence, but some could describe it");
      }
      facts.substitutes = serviceFact(related(substitutes, summary), unparsed.length === 0, sources, RULES.substituteSearch, "No substitute is tied to this service by evidence, but some could apply to it");

      // A development proxy is environment configuration, so no matching route is never a bounded absence.
      if (summary.sameOrigin) {
        const matched = new Map<string, Route>();
        for (const path of summary.paths) {
          const route = routes.find((item) => proxies(item.route, path));
          if (route) matched.set(`${route.path}\u0000${route.route}`, route);
        }
        for (const route of matched.values()) extra.push({ key: summary.key, client, callSites: [], facts: { proxy: { basis: "observed", value: { kind: "dev_proxy", route: route.route, target: route.target, configuration: route.path }, evidence: [route.evidence], rule: route.rule } } });
      }
      context.service({ key: summary.key, client, callSites: [], facts });
      for (const candidate of extra) context.service(candidate);
    }
  },
};

// ---------------------------------------------------------------------------
// Access signals

async function reportAccess(context: DetectorContext, trees: readonly SyntaxTree[], signal: (kind: string) => MatchedRule[], summaries: readonly ServiceSummary[], sources: readonly string[], unparsed: readonly string[]) {
  const dockerfiles = readableInputs(context, "dockerfile").map((input) => input.path);
  const references = [...trees.flatMap((tree) => environmentReferences(context, tree)), ...(await dockerfileVariables(context, dockerfiles))];
  for (const [name, group] of groupBy(references, (reference) => reference.name)) {
    const kind = classify(name);
    if (!kind) continue;
    const category = kind === "proxy_variable" || kind === "gateway_configuration" ? "egress_routes" : "access_signals";
    const readFrom = [...new Set(group.map((reference) => reference.source))].sort(compareCodeUnits);
    context.fact({ category, key: `name:${name}`, value: { kind, name, read_from: readFrom }, basis: "observed", evidence: group.map((reference) => reference.evidence), rule: group.some((reference) => reference.source !== "Dockerfile") ? RULES.environment : RULES.dockerfile });
  }

  // Only existence is visible: the read policy never admits a credential file's bytes.
  for (const input of inventoryOf(context).inputs) {
    const entry = input.kind === "sensitive" ? context.reader.entry(input.path) : undefined;
    const format = sensitiveFormat(input.path);
    if (entry && format) context.fact({ category: "access_signals", key: `file:${input.path}`, value: { kind: "credential_file", path: input.path, format: format.format, label: format.label }, basis: "observed", evidence: [context.entry(entry, RULES.credentialFile)], rule: RULES.credentialFile });
  }

  for (const [module, group] of groupBy(signal("auth-library"), (match) => literalText(match.captures.module) ?? "")) {
    if (module) context.fact({ category: "access_signals", key: `library:${module}`, value: { kind: "authentication_library", module }, basis: "observed", evidence: group.map((match) => match.evidence), rule: group[0]!.rule.id });
  }

  for (const summary of summaries) {
    const zone = summary.origin === null ? null : networkZone(summary.origin);
    if (!zone) continue;
    const value = { kind: "network_zone", origin: summary.origin, zone };
    if (zone === "internal_domain") context.fact({ category: "access_signals", key: `zone:${summary.origin}`, value, basis: "inferred", evidence: summary.callSites, rule: RULES.networkZone, reasoning: "The service's host name ends in a suffix conventionally reserved for private networks, so it is likely reachable only from inside one." });
    else context.fact({ category: "access_signals", key: `zone:${summary.origin}`, value, basis: "observed", evidence: summary.callSites, rule: RULES.networkZone });
  }

  const skipped = [...unparsed, ...unanalyzedInputs(context, "dockerfile").map((input) => input.path)].sort(compareCodeUnits);
  context.search({ category: "access_signals", rule: RULES.accessSearch, surface: [...sources, ...dockerfiles].sort(compareCodeUnits), complete: true, skipped });
}

/** A variable name's signal, from its words: `ORDERS_API_TOKEN` and `ordersApiToken` both name a credential. */
export function classify(name: string): Classification | null {
  const words = name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toUpperCase()
    .split(/[^A-Z0-9]+/)
    .filter(Boolean);
  if (words.includes("PROXY")) return "proxy_variable";
  if (words.includes("GATEWAY")) return "gateway_configuration";
  if (words.some((word, index) => CREDENTIAL_WORDS.has(word) || (word === "KEY" && KEY_QUALIFIERS.has(words[index - 1] ?? "")))) return "credential_reference";
  if (words.some((word) => CERTIFICATE_WORDS.has(word))) return "certificate_reference";
  if (words.some((word, index) => AUTHENTICATION_WORDS.has(word) || (word === "ID" && words[index - 1] === "CLIENT"))) return "authentication_configuration";
  return null;
}

/** Every environment key a file reads by name: `process.env.NAME`, `process.env["NAME"]`, `import.meta.env.NAME`, and destructuring. */
function environmentReferences(context: DetectorContext, tree: SyntaxTree): Reference[] {
  const references: Reference[] = [];
  const push = (name: string | null, source: ConfigSource, node: ts.Node) => {
    if (name) references.push({ name, source, evidence: nodeEvidence(context, tree, node, RULES.environment) });
  };
  tree.walk((node) => {
    if (ts.isPropertyAccessExpression(node) || ts.isElementAccessExpression(node)) {
      const source = environmentOf(node.expression);
      if (!source) return;
      if (ts.isPropertyAccessExpression(node)) push(node.name.text, source, node);
      else {
        const key = unwrap(node.argumentExpression);
        push(ts.isStringLiteral(key) || ts.isNoSubstitutionTemplateLiteral(key) ? key.text : null, source, node);
      }
    } else if (ts.isVariableDeclaration(node) && node.initializer && ts.isObjectBindingPattern(node.name)) {
      const source = environmentOf(node.initializer);
      if (!source) return;
      for (const element of node.name.elements) push(element.propertyName ? propertyName(element.propertyName) : ts.isIdentifier(element.name) ? element.name.text : null, source, element);
    }
  });
  return references;
}

function environmentOf(expression: ts.Node): ConfigSource | null {
  const target = unwrap(expression);
  if (!ts.isPropertyAccessExpression(target) || target.name.text !== "env") return null;
  const owner = unwrap(target.expression);
  if (ts.isIdentifier(owner) && owner.text === "process") return "process.env";
  if (ts.isMetaProperty(owner) && owner.keywordToken === ts.SyntaxKind.ImportKeyword && owner.name.text === "meta") return "import.meta.env";
  return null;
}

/** Names a Dockerfile declares with ENV or ARG, across continuation lines. Values are never recorded. */
async function dockerfileVariables(context: DetectorContext, paths: readonly string[]): Promise<Reference[]> {
  const references: Reference[] = [];
  for (const path of paths) {
    const content = await context.text(path);
    if (!content?.text) continue;
    const lines = content.text.split("\n");
    for (let index = 0; index < lines.length; index++) {
      const start = index;
      let logical = lines[index]!;
      while (/\\\s*$/.test(logical) && index + 1 < lines.length) logical = logical.replace(/\\\s*$/, " ") + lines[++index];
      const instruction = /^\s*(ENV|ARG)\s+(.*)$/i.exec(logical);
      if (!instruction) continue;
      const keyword = instruction[1]!.toUpperCase();
      // Quoted values can contain `NAME=`; only unquoted words declare names.
      const words = instruction[2]!.replace(/"(?:[^"\\]|\\.)*"|'[^']*'/g, '""').trim().split(/\s+/);
      const names = keyword === "ENV" && !words[0]?.includes("=") ? [words[0]] : words.map((word) => /^([A-Za-z_][A-Za-z0-9_]*)=/.exec(word)?.[1] ?? (keyword === "ARG" ? word : undefined));
      const evidence = context.lines(content, RULES.dockerfile, start + 1, index + 1);
      for (const name of names) if (name && /^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) references.push({ name, source: "Dockerfile", evidence });
    }
  }
  return references;
}

/** The network a literal host is reachable from, when its address or name says so. */
export function networkZone(origin: string): "loopback" | "private_address" | "internal_domain" | null {
  let host: string;
  try {
    host = new URL(origin).hostname.toLowerCase().replace(/^\[|\]$/g, "");
  } catch {
    return null;
  }
  if (host === "localhost" || host.endsWith(".localhost") || host === "::1" || host === "0.0.0.0" || /^127\.\d+\.\d+\.\d+$/.test(host)) return "loopback";
  if (/^10\.\d+\.\d+\.\d+$/.test(host) || /^192\.168\.\d+\.\d+$/.test(host) || /^172\.(1[6-9]|2\d|3[01])\.\d+\.\d+$/.test(host) || /^f[cd][0-9a-f]{2}:/.test(host)) return "private_address";
  if (/\.(internal|local|corp|intranet|lan|private|home\.arpa)$/.test(host)) return "internal_domain";
  return null;
}

// ---------------------------------------------------------------------------
// Proxies and gateways

function reportEgress(context: DetectorContext, signal: (kind: string) => MatchedRule[], sources: readonly string[], unparsed: readonly string[]): Route[] {
  const routes: Route[] = [];
  const skipped = new Set(unparsed);
  for (const match of signal("dev-proxy")) {
    const proxy = match.captures.proxy;
    if (proxy?.kind !== "object" || !proxy.complete) {
      context.diagnostic(match.tree.path, "unsupported_value", "Some development proxy routes are computed, so they are not recorded");
      skipped.add(match.tree.path);
    }
    if (proxy?.kind !== "object") continue;
    for (const [route, config] of proxy.properties) {
      const target = config.kind === "object" ? config.properties.get("target") : config;
      const node = config.node.getSourceFile() === match.tree.file ? config.node : match.node;
      routes.push({ route, target: target ? captureValue(target) : { kind: "absent" }, path: match.tree.path, evidence: nodeEvidence(context, match.tree, node, match.rule.id), rule: match.rule.id });
    }
  }
  for (const match of signal("proxy-middleware")) {
    const first = match.captures.first;
    const legacy = literalText(first);
    const options = legacy === null ? first : match.captures.options;
    const property = (name: string) => (options?.kind === "object" ? options.properties.get(name) : undefined);
    // `app.use("/api", createProxyMiddleware({ target }))` mounts the proxy on the use path.
    const parent = match.node.parent;
    const mount = ts.isCallExpression(parent) && ts.isPropertyAccessExpression(parent.expression) && parent.expression.name.text === "use" && parent.arguments.length > 1 && parent.arguments[0] !== match.node ? unwrap(parent.arguments[0]!) : null;
    const mounted = mount && ts.isStringLiteral(mount) ? mount.text : null;
    const route = legacy ?? literalText(property("pathFilter")) ?? mounted ?? "/";
    const target = property("target");
    routes.push({ route: redactCredentials(route), target: target ? captureValue(target) : { kind: "absent" }, path: match.tree.path, evidence: match.evidence, rule: match.rule.id });
  }
  for (const route of routes) context.fact({ category: "egress_routes", key: `dev-proxy:${route.path}:${route.route}`, value: { kind: "dev_proxy", route: route.route, target: route.target, configuration: route.path }, basis: "observed", evidence: [route.evidence], rule: route.rule });

  for (const entry of context.reader.entries) {
    const name = entry.path.slice(entry.path.lastIndexOf("/") + 1);
    const server = entry.type === "file" && !isVendored(entry.path) ? GATEWAY_FILES.find(([matches]) => matches(name))?.[1] : undefined;
    if (!server) continue;
    // Recognized from the listing only, so routes it defines stay unknown.
    context.fact({ category: "egress_routes", key: `gateway-file:${entry.path}`, value: { kind: "gateway_configuration_file", path: entry.path, server, rules: "not_analyzed" }, basis: "observed", evidence: [context.entry(entry, RULES.gatewayFile)], rule: RULES.gatewayFile });
    skipped.add(entry.path);
  }
  context.search({ category: "egress_routes", rule: RULES.egressSearch, surface: sources, complete: true, skipped: [...skipped].sort(compareCodeUnits) });
  return routes;
}

/** Whether a proxy route handles a request path, by prefix. Pattern routes (regular expressions, globs) are never interpreted. */
function proxies(route: string, path: string): boolean {
  return !/[\^*?([{]/.test(route) && path.startsWith(route);
}

// ---------------------------------------------------------------------------
// API contracts

async function reportContracts(context: DetectorContext, trees: readonly SyntaxTree[], imports: ImportGraph, summaries: readonly ServiceSummary[], sources: readonly string[], unparsed: readonly string[]): Promise<{ candidates: Candidate[]; surface: string[]; complete: boolean }> {
  const candidates: Candidate[] = [];
  const skipped = new Set([...unparsed, ...unanalyzedInputs(context, "openapi", "graphql-schema").map((input) => input.path)]);
  const openapiInputs = readableInputs(context, "openapi");
  const graphqlInputs = readableInputs(context, "graphql-schema");
  const record = (value: Value | undefined) => (value && typeof value === "object" && !Array.isArray(value) ? value : null);

  for (const input of openapiInputs) {
    const format = input.path.endsWith(".json") ? "json" : "yaml";
    const parsed = await context.parsed(input.path, format);
    const root = record(parsed?.value);
    const version = typeof root?.openapi === "string" ? root.openapi : typeof root?.swagger === "string" ? root.swagger : null;
    if (!parsed || !root || version === null) {
      if (parsed) context.diagnostic(input.path, "unsupported_shape", "The file is not an OpenAPI or Swagger document");
      skipped.add(input.path);
      continue;
    }
    const servers = (Array.isArray(root.servers) ? root.servers : []).flatMap((server) => {
      const url = record(server)?.url;
      return typeof url === "string" ? [redactCredentials(url)] : [];
    });
    // Swagger 2 states one host and base path.
    if (typeof root.host === "string") servers.push(redactCredentials(`${Array.isArray(root.schemes) && typeof root.schemes[0] === "string" ? root.schemes[0] : "https"}://${root.host}${typeof root.basePath === "string" ? root.basePath : ""}`));
    const endpoints = servers.map((url) => fromText(url));
    const origins = endpoints.flatMap((endpoint) => (endpoint.kind === "literal" ? [endpoint.origin] : []));
    const basePaths = endpoints.length ? [...new Set(endpoints.map((endpoint) => (endpoint.path ?? "/").replace(/\/+$/, "")))] : [""];
    const operations = Object.keys(record(root.paths) ?? {}).sort(compareCodeUnits);
    const title = record(root.info)?.title;
    const evidence = context.pointer(parsed.content, RULES.openapi, format, typeof root.openapi === "string" ? "/openapi" : "/swagger");
    context.fact({ category: "api_contracts", key: input.path, value: { kind: "openapi", path: input.path, version, title: typeof title === "string" ? title : null, servers: [...new Set(servers)].sort(compareCodeUnits), operations: operations.length }, basis: "observed", evidence: [evidence], rule: RULES.openapi });

    // A request path under a server's base path that names one of the document's operations.
    const describes = (summary: ServiceSummary) => summary.paths.some((path) => basePaths.some((base) => (base === "" || path === base || path.startsWith(`${base}/`)) && operations.some((operation) => pathsMatch(operation, path.slice(base.length) || "/"))));
    candidates.push({
      item: { kind: "openapi", path: input.path },
      evidence,
      relation: (summary) => {
        if (summary.protocol !== "http") return { tie: "excluded" };
        if (summary.origin !== null && origins.includes(summary.origin)) return { tie: "observed", association: "server_origin" };
        if (summary.origin !== null && origins.length > 0) return { tie: "excluded" };
        if (describes(summary)) return { tie: "observed", association: "operation_paths" };
        if (summary.paths.length > 0 && operations.length > 0) return { tie: "excluded" };
        if (summary.client === "generated") return { tie: "inferred", association: "generated_client", reasoning: "The service is called through a client generated from an OpenAPI document, and this committed document could be its source; its servers and paths neither confirm nor rule it out." };
        return { tie: "possible" };
      },
    });
  }

  const graphqlServices = summaries.filter((summary) => summary.protocol === "graphql").length;
  for (const input of graphqlInputs) {
    const content = await context.text(input.path);
    const entry = context.reader.entry(input.path);
    if (!content?.text || !entry) {
      skipped.add(input.path);
      continue;
    }
    const text = content.text.replace(/#[^\n]*/g, "");
    const definitions = [...text.matchAll(/^\s*(?:extend\s+)?(?:type|input|enum|interface|union|scalar|schema)\b/gm)].length;
    const operations = [...text.matchAll(/^\s*(query|mutation|subscription)\s+([A-Za-z_][A-Za-z0-9_]*)/gm)].map((match) => `${match[1]} ${match[2]}`).sort(compareCodeUnits);
    const evidence = context.entry(entry, RULES.graphql);
    context.fact({ category: "api_contracts", key: input.path, value: { kind: definitions > 0 ? "graphql_schema" : "graphql_operations", path: input.path, definitions, operations }, basis: "observed", evidence: [evidence], rule: RULES.graphql });
    // Operation documents are attributed with the service's operations, not as its contract.
    if (definitions === 0) continue;
    candidates.push({
      item: { kind: "graphql_schema", path: input.path },
      evidence,
      relation: (summary) => {
        if (summary.protocol !== "graphql") return { tie: "excluded" };
        return graphqlServices === 1 ? { tie: "inferred", association: "only_graphql_service", reasoning: "The repository commits this GraphQL schema and has one GraphQL service, so the schema could describe it." } : { tie: "possible" };
      },
    });
  }

  for (const tree of trees) {
    const generated = generatedSchema(tree);
    if (!generated) continue;
    const evidence = context.lines(tree.content, RULES.generatedSchema, generated.lines.start, generated.lines.end);
    context.fact({ category: "api_contracts", key: tree.path, value: { kind: "generated_schema", path: tree.path, generator: generated.generator, contract: generated.contract }, basis: "observed", evidence: [evidence], rule: RULES.generatedSchema });
    candidates.push({
      item: { kind: "generated_schema", path: tree.path },
      evidence,
      relation: (summary) => {
        const family = summary.protocol === "graphql" ? "graphql" : summary.protocol === "http" ? "openapi" : null;
        if (family !== generated.contract) return { tie: "excluded" };
        return imports.reaches(callSiteFiles(summary), tree.path) ? { tie: "observed", association: "imported_at_call_site" } : { tie: "possible" };
      },
    });
  }

  const surface = [...new Set([...sources, ...openapiInputs.map((input) => input.path), ...graphqlInputs.map((input) => input.path)])].sort(compareCodeUnits);
  context.search({ category: "api_contracts", rule: RULES.contractSearch, surface, complete: true, skipped: [...skipped].sort(compareCodeUnits) });
  return { candidates, surface, complete: skipped.size === 0 };
}

/** A leading comment naming a known contract generator marks a generated schema. */
function generatedSchema(tree: SyntaxTree): { generator: string; contract: "openapi" | "graphql"; lines: { start: number; end: number } } | null {
  const text = tree.content.text ?? "";
  for (const range of ts.getLeadingCommentRanges(text, text.startsWith("#!") ? text.indexOf("\n") + 1 : 0) ?? []) {
    const comment = text.slice(range.pos, range.end);
    const found = GENERATED.test(comment) ? GENERATORS.find(([pattern]) => pattern.test(comment)) : undefined;
    if (!found) continue;
    const line = (position: number) => tree.file.getLineAndCharacterOfPosition(position).line + 1;
    return { generator: found[1], contract: found[2], lines: { start: line(range.pos), end: line(range.end) } };
  }
  return null;
}

// ---------------------------------------------------------------------------
// Test substitutes

function reportSubstitutes(context: DetectorContext, signal: (kind: string) => MatchedRule[], imports: ImportGraph, summaries: readonly ServiceSummary[]): Candidate[] {
  const candidates: Candidate[] = [];
  const report = (key: string, value: Record<string, Value>, match: MatchedRule, relation?: Candidate["relation"]) => {
    context.fact({ category: "test_substitutes", key, value, basis: "observed", evidence: [match.evidence], rule: match.rule.id });
    if (relation) candidates.push({ item: { ...value, path: match.tree.path }, evidence: match.evidence, relation });
  };
  const at = (match: MatchedRule) => `${match.tree.path}:${match.tree.lines(match.node).start}`;
  const graphqlServices = summaries.filter((summary) => summary.protocol === "graphql").length;

  for (const match of signal("request-interceptor")) {
    const url = match.captures.url;
    const target = interceptedEndpoint(match.tree, url);
    report(`interceptor:${at(match)}`, { kind: "request_interceptor", library: match.rule.id === "services.substitute.nock" ? "nock" : "msw", url: url ? captureValue(url) : { kind: "absent" } }, match, (summary) => interception(target, summary));
  }
  for (const match of signal("graphql-interceptor")) {
    const operation = match.captures.operation;
    report(`interceptor:${at(match)}`, { kind: "graphql_interceptor", library: "msw", operation: operation ? captureValue(operation) : { kind: "absent" } }, match, (summary) => {
      if (summary.protocol !== "graphql") return { tie: "excluded" };
      return graphqlServices === 1 ? { tie: "inferred", association: "only_graphql_service", reasoning: "The test intercepts GraphQL operations and the repository has one GraphQL service; the handlers are not shown to match its schema." } : { tie: "possible" };
    });
  }
  // A mock server is tied through the handlers it serves, not by itself.
  for (const match of signal("mock-server")) report(`mock-server:${at(match)}`, { kind: "mock_server", library: literalText(match.captures.module) ?? literalText(match.captures.calleeModule) ?? "msw" }, match);

  for (const match of [...signal("module-mock"), ...signal("module-mock-candidate")]) {
    if (match.rule.id === "services.substitute.global-module-mock" && !globalMockReceiver(match)) continue;
    const module = literalText(match.captures.module);
    if (!module) continue;
    const relative = module.startsWith("./") || module.startsWith("../");
    const resolved = relative ? imports.resolve(match.tree.path, module) : null;
    report(`module-mock:${match.tree.path}:${module}`, { kind: "module_mock", module, ...(resolved !== null && { resolved }) }, match, (summary) => {
      if (relative) {
        if (resolved === null) return { tie: "possible" };
        return imports.reaches(callSiteFiles(summary), resolved) ? { tie: "observed", association: "mocks_call_site_module" } : { tie: "excluded" };
      }
      // Path aliases such as `@/api` are not resolved, so they could name any module.
      if (/^[@~#]\//.test(module)) return { tie: "possible" };
      return module === summary.pkg || (CLIENT_PACKAGES[summary.client] ?? []).includes(module) ? { tie: "observed", association: "mocks_client_package" } : { tie: "excluded" };
    });
  }
  for (const match of signal("fetch-stub")) {
    // A stub replaces fetch only for the code its test runs: tied through the test's own imports, possible through deeper ones.
    report(`global-stub:${at(match)}`, { kind: "global_stub", global: "fetch" }, match, (summary) => {
      if (!FETCH_CLIENTS.has(summary.client)) return NON_FETCH_CLIENTS.has(summary.client) ? { tie: "excluded" } : { tie: "possible" };
      return callSiteFiles(summary).some((file) => imports.reaches([match.tree.path], file)) ? { tie: "inferred", association: "global_fetch", reasoning: "A test that imports this service's calls replaces the global fetch they use; the stub is not shown to answer them like the service." } : { tie: "possible" };
    });
  }

  const fixtureDirectories = context.reader.entries.filter((entry) => entry.type === "tree" && !isVendored(entry.path) && FIXTURE_DIRECTORIES.has(entry.path.slice(entry.path.lastIndexOf("/") + 1)));
  for (const entry of fixtureDirectories) context.fact({ category: "test_substitutes", key: `fixtures:${entry.path}`, value: { kind: "fixture_directory", path: entry.path }, basis: "observed", evidence: [context.entry(entry, RULES.fixture)], rule: RULES.fixture });
  // A fixture file is tied only through a test file whose own substitute is tied to the service.
  const inFixtures = (path: string) => fixtureDirectories.some((entry) => path.startsWith(`${entry.path}/`));
  for (const substitute of [...candidates]) {
    for (const fixture of imports.of(substitute.evidence.path).filter(inFixtures)) {
      const entry = context.reader.entry(fixture);
      if (!entry) continue;
      candidates.push({
        item: { kind: "fixture", path: fixture },
        evidence: context.entry(entry, RULES.fixture),
        relation: (summary) => {
          const tie = substitute.relation(summary).tie;
          return tie === "observed" || tie === "inferred" ? { tie: "inferred", association: "imported_with_substitute", reasoning: "The fixture is imported by a test file whose substitute is tied to this service; it is not shown to be that substitute's data." } : { tie: "excluded" };
        },
      });
    }
  }
  return candidates;
}

/** A bare `vi.mock` or `jest.mock` refers to the test runner's global only when the file binds no such name itself. */
function globalMockReceiver(match: MatchedRule): boolean {
  const callee = ts.isCallExpression(match.node) ? unwrap(match.node.expression) : null;
  const receiver = callee && ts.isPropertyAccessExpression(callee) ? unwrap(callee.expression) : null;
  return receiver !== null && ts.isIdentifier(receiver) && (receiver.text === "jest" || receiver.text === "vi") && !match.tree.binding(receiver.text);
}

type Intercepted = ReturnType<typeof deriveEndpoint> | { kind: "any_origin"; path: string };

function interceptedEndpoint(tree: SyntaxTree, url: StaticValue | undefined): Intercepted {
  const text = literalText(url);
  // msw's `*/path` matches the path on any origin.
  if (text?.startsWith("*/")) return { kind: "any_origin", path: text.slice(1) };
  return deriveEndpoint(tree, undefined, url);
}

function interception(target: Intercepted, summary: ServiceSummary): Relation {
  const bare = summary.protocol === "http" ? summary.key : summary.key.slice(summary.protocol.length + 1);
  const byPath = (path: string | null): Relation => {
    if (path === null || summary.paths.length === 0) return { tie: "possible" };
    return summary.paths.some((own) => pathsMatch(path, own)) ? { tie: "observed", association: "intercepted_path" } : { tie: "excluded" };
  };
  switch (target.kind) {
    case "literal":
      if (summary.origin === null) return { tie: "possible" };
      return summary.origin === target.origin ? { tie: "observed", association: "intercepted_origin" } : { tie: "excluded" };
    case "relative":
      if (summary.origin !== null) return { tie: "excluded" };
      return summary.sameOrigin ? byPath(target.path) : { tie: "possible" };
    case "any_origin":
      return byPath(target.path);
    case "configured":
      return bare === `config:${target.source}:${target.key}` ? { tie: "observed", association: "intercepted_configuration_key" } : { tie: "possible" };
    default:
      return { tie: "possible" };
  }
}

// ---------------------------------------------------------------------------
// Association

function related(candidates: readonly Candidate[], summary: ServiceSummary) {
  const observed: Tie[] = [];
  const inferred: Tie[] = [];
  let possible = 0;
  for (const candidate of candidates) {
    const relation = candidate.relation(summary);
    if (relation.tie === "observed" || relation.tie === "inferred") (relation.tie === "observed" ? observed : inferred).push({ candidate, relation });
    else if (relation.tie === "possible") possible++;
  }
  return { observed, inferred, possible };
}

/** One candidate for all of a service's ties: observed only when every tie is. */
function associate(ties: readonly Tie[]): ServiceFactCandidate {
  const reasons = [...new Set(ties.flatMap((tie) => (tie.relation.tie === "inferred" ? [tie.relation.reasoning] : [])))].sort(compareCodeUnits);
  return {
    basis: reasons.length ? "inferred" : "observed",
    value: uniqueSorted(ties.map((tie) => ({ ...tie.candidate.item, association: tie.relation.association }))),
    evidence: ties.map((tie) => tie.candidate.evidence),
    rule: RULES.association,
    ...(reasons.length > 0 && { reasoning: reasons.join(" ") }),
  };
}

function serviceFact(ties: ReturnType<typeof related>, complete: boolean, surface: readonly string[], rule: string, openReason: string): ServiceFactCandidate {
  const all = [...ties.observed, ...ties.inferred];
  if (all.length) return associate(all);
  if (!complete) return { basis: "unknown", value: { reason: "Some inputs could not be searched" }, evidence: [], rule };
  if (ties.possible > 0) return { basis: "unknown", value: { reason: openReason }, evidence: [], rule };
  return { basis: "absent", value: null, evidence: [], rule, search: { surface, complete: true, skipped: [] } };
}

function callSiteFiles(summary: ServiceSummary): string[] {
  return [...new Set(summary.callSites.map((evidence) => evidence.path))];
}

/** Whether a route pattern (`:id`, `{id}`, `*`) and a request path (`{param}`) name the same route. */
export function pathsMatch(pattern: string, path: string): boolean {
  const split = (value: string) => value.split(/[?#]/)[0]!.split("/").filter(Boolean);
  const wild = (segment: string) => segment.startsWith(":") || /^\{[^}]*\}$/.test(segment) || segment === "*";
  const left = split(pattern);
  const right = split(path);
  for (let index = 0; index < left.length; index++) {
    // A trailing `*` matches the rest of the path.
    if (left[index] === "*" && index === left.length - 1) return right.length >= index;
    if (index >= right.length || !(wild(left[index]!) || wild(right[index]!) || left[index] === right[index])) return false;
  }
  return left.length === right.length;
}

// ---------------------------------------------------------------------------
// Relative imports

interface ImportGraph {
  /** Resolves a relative specifier from +from+ to a committed path, or null. */
  resolve(from: string, specifier: string): string | null;
  /** Committed paths +file+ imports with relative specifiers. */
  of(file: string): string[];
  /** Whether +target+ is one of +files+ or imported directly by one of them. */
  reaches(files: readonly string[], target: string): boolean;
}

function importGraph(context: DetectorContext, trees: ReadonlyMap<string, SyntaxTree>): ImportGraph {
  const resolve = (from: string, specifier: string): string | null => {
    const segments = from.split("/").slice(0, -1);
    for (const part of specifier.split("/")) {
      if (part === "..") {
        if (segments.length === 0) return null;
        segments.pop();
      } else if (part !== "." && part !== "") segments.push(part);
    }
    const base = segments.join("/");
    // TypeScript's ESM style names the emitted `.js` file for a `.ts` source.
    const stems = /\.[cm]?js$/.test(base) ? [base, base.replace(/\.([cm]?)js$/, ".$1ts"), base.replace(/\.[cm]?js$/, ".tsx"), base.replace(/\.[cm]?js$/, ".d.ts")] : [base];
    for (const candidate of [...stems.flatMap((stem) => MODULE_EXTENSIONS.map((extension) => stem + extension)), ...MODULE_EXTENSIONS.slice(1).map((extension) => `${base}/index${extension}`)]) {
      const entry = context.reader.entry(candidate);
      if (entry && (entry.type === "file" || entry.type === "executable")) return candidate;
    }
    return null;
  };
  const graph = new Map<string, string[]>();
  for (const [path, tree] of trees) {
    const targets = new Set<string>();
    for (const statement of tree.file.statements) {
      const specifier = (ts.isImportDeclaration(statement) || ts.isExportDeclaration(statement)) && statement.moduleSpecifier && ts.isStringLiteral(statement.moduleSpecifier) ? statement.moduleSpecifier.text : null;
      const resolved = specifier && (specifier.startsWith("./") || specifier.startsWith("../")) ? resolve(path, specifier) : null;
      if (resolved) targets.add(resolved);
    }
    graph.set(path, [...targets].sort(compareCodeUnits));
  }
  return {
    resolve,
    of: (file) => graph.get(file) ?? [],
    reaches: (files, target) => files.some((file) => file === target || (graph.get(file) ?? []).includes(target)),
  };
}

// ---------------------------------------------------------------------------

function groupBy<T>(items: readonly T[], key: (item: T) => string): [string, T[]][] {
  const groups = new Map<string, T[]>();
  for (const item of items) {
    const group = groups.get(key(item));
    if (group) group.push(item);
    else groups.set(key(item), [item]);
  }
  return [...groups.entries()].sort(([a], [b]) => compareCodeUnits(a, b));
}

function uniqueSorted(values: readonly Value[]): Value[] {
  const seen = new Map<string, Value>();
  for (const value of values) seen.set(JSON.stringify(value), value);
  return [...seen.entries()].sort(([a], [b]) => compareCodeUnits(a, b)).map(([, value]) => value);
}
